# Generated by Django 5.1.1 on 2025-11-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título gerado automaticamente baseado na primeira mensagem', max_length=200, verbose_name='Título da Conversa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Se False, a sessão foi encerrada pelo usuário', verbose_name='Sessão Ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], help_text='Quem enviou a mensagem', max_length=10, verbose_name='Papel')),
                ('content', models.TextField(help_text='Texto da mensagem', verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Número de tokens gastos (apenas mensagens do assistente)', null=True, verbose_name='Tokens Utilizados')),
                ('response_time', models.FloatField(blank=True, help_text='Tempo que a IA levou para responder (apenas mensagens do assistente)', null=True, verbose_name='Tempo de Resposta (segundos)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_literario.chatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.JSONField(blank=True, default=list, help_text='Lista de gêneros literários mencionados pelo usuário', verbose_name='Gêneros Favoritos')),
                ('favorite_authors', models.JSONField(blank=True, default=list, help_text='Lista de autores mencionados pelo usuário', verbose_name='Autores Favoritos')),
                ('reading_preferences', models.JSONField(blank=True, default=dict, help_text='Outras preferências (e.g., tamanho de livro, complexidade, etc.)', verbose_name='Preferências de Leitura')),
                ('interests', models.JSONField(blank=True, default=list, help_text='Tópicos de interesse do usuário (cinema, animes, games, etc.)', verbose_name='Interesses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_context', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Contexto de Conversa',
                'verbose_name_plural': 'Contextos de Conversa',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_lit_user_id_d22924_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_lit_user_id_02c54c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_lit_session_3cd273_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chatbot_lit_role_bddf29_idx'),
        ),
    ]
