# Generated by Django 5.1.1 on 2025-12-03 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0001_initial'),
        ('core', '0016_alter_section_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Corrigido em'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Corrigido Por'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='corrected_content',
            field=models.TextField(blank=True, help_text='Conteúdo corrigido pelo admin', verbose_name='Conteúdo Corrigido'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='has_correction',
            field=models.BooleanField(default=False, help_text='Se esta mensagem foi corrigida por um admin', verbose_name='Tem Correção'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rag_data_used',
            field=models.JSONField(blank=True, help_text='Dados que o RAG injetou no prompt', null=True, verbose_name='Dados RAG Usados'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rag_intent_detected',
            field=models.CharField(blank=True, help_text='Intent RAG detectado (author_query, book_search, etc)', max_length=50, verbose_name='Intent RAG Detectado'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('helpful', 'Útil'), ('not_helpful', 'Não Útil'), ('incorrect', 'Incorreto')], help_text='Feedback do usuário sobre esta resposta', max_length=20, verbose_name='Feedback do Usuário'),
        ),
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(choices=[('author_query', 'Pergunta sobre Autor'), ('book_info', 'Informação sobre Livro'), ('recommendation', 'Recomendação'), ('series_info', 'Informação sobre Série'), ('category_search', 'Busca por Categoria'), ('general', 'Conhecimento Geral')], default='general', max_length=50, verbose_name='Tipo de Conhecimento')),
                ('original_question', models.TextField(help_text='Pergunta original do usuário que gerou a correção', verbose_name='Pergunta Original')),
                ('incorrect_response', models.TextField(blank=True, help_text='Resposta incorreta original da IA (para referência)', verbose_name='Resposta Incorreta')),
                ('correct_response', models.TextField(help_text='Resposta correta fornecida/aprovada pelo admin', verbose_name='Resposta Correta')),
                ('keywords', models.JSONField(default=list, help_text='Lista de palavras-chave extraídas automaticamente da pergunta', verbose_name='Palavras-chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('times_used', models.IntegerField(default=0, help_text='Quantas vezes este conhecimento foi utilizado em conversas', verbose_name='Vezes Usado')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Última vez que este conhecimento foi usado', null=True, verbose_name='Último Uso')),
                ('is_active', models.BooleanField(default=True, help_text='Se este conhecimento está ativo e deve ser usado pelo chatbot', verbose_name='Ativo')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confiança nesta correção (0.0 a 1.0). Quanto maior, mais prioritário', verbose_name='Confiança')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas do admin sobre esta correção', verbose_name='Notas do Admin')),
                ('created_by', models.ForeignKey(help_text='Admin que criou esta correção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('related_author', models.ForeignKey(blank=True, help_text='Autor relacionado a esta correção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='core.author', verbose_name='Autor Relacionado')),
                ('related_book', models.ForeignKey(blank=True, help_text='Livro relacionado a esta correção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='core.book', verbose_name='Livro Relacionado')),
            ],
            options={
                'verbose_name': 'Conhecimento do Chatbot',
                'verbose_name_plural': 'Base de Conhecimento do Chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='knowledge_base_used',
            field=models.ForeignKey(blank=True, help_text='Conhecimento da base que foi usado (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_instances', to='chatbot_literario.chatbotknowledge', verbose_name='Knowledge Base Usado'),
        ),
        migrations.AddIndex(
            model_name='chatbotknowledge',
            index=models.Index(fields=['knowledge_type', 'is_active'], name='chatbot_lit_knowled_ce8249_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotknowledge',
            index=models.Index(fields=['related_book'], name='chatbot_lit_related_321c53_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotknowledge',
            index=models.Index(fields=['related_author'], name='chatbot_lit_related_81f9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotknowledge',
            index=models.Index(fields=['is_active', 'confidence_score'], name='chatbot_lit_is_acti_9fa751_idx'),
        ),
    ]
