# Generated by Django 5.1.1 on 2026-05-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0002_chatmessage_corrected_at_chatmessage_corrected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='chat_type',
            field=models.CharField(choices=[('literario', 'Literário (Dbit)'), ('suporte', 'Suporte CG.BookStore')], default='literario', help_text='Literário (Dbit) ou Suporte ao cliente', max_length=20, verbose_name='Tipo de Chat'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, help_text='Chave da sessão Django para identificar visitantes não autenticados', max_length=40, null=True, verbose_name='Chave de Sessão Anônima'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Nulo para sessões anônimas (chat de suporte)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chat_type', '-updated_at'], name='chatbot_lit_chat_ty_388bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_key'], name='chatbot_lit_session_753fae_idx'),
        ),
    ]
