# Generated by Django 5.1.1 on 2026-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_literario', '0003_add_chat_type_and_anonymous_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotknowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('author_query', 'Pergunta sobre Autor'), ('book_info', 'Informação sobre Livro'), ('recommendation', 'Recomendação'), ('series_info', 'Informação sobre Série'), ('category_search', 'Busca por Categoria'), ('support_query', 'Suporte ao Cliente'), ('general', 'Conhecimento Geral')], default='general', max_length=50, verbose_name='Tipo de Conhecimento'),
        ),
    ]
