# Generated by Django 5.1.1 on 2025-12-09 17:24

import django_ckeditor_5.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_section_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Ex: fas fa-newspaper, fas fa-calendar, fas fa-microphone', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#3498db', help_text='Código hexadecimal da cor (ex: #3498db)', max_length=7, verbose_name='Cor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Desinscrito em')),
            ],
            options={
                'verbose_name': 'Inscrição Newsletter',
                'verbose_name_plural': 'Inscrições Newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo/Chamada')),
                ('content_type', models.CharField(choices=[('news', '📰 Notícia'), ('interview', '🎤 Entrevista'), ('event', '📅 Evento'), ('announcement', '📢 Anúncio'), ('tip', '💡 Dica da Semana'), ('highlight', '⭐ Destaque'), ('schedule', '📆 Programação'), ('article', '📝 Artigo'), ('guide', '📖 Guia'), ('review', '⭐ Resenha')], default='news', max_length=20, verbose_name='Tipo de Conteúdo')),
                ('excerpt', models.TextField(help_text='Texto curto para exibição em cards e listas (máx 500 caracteres)', max_length=500, verbose_name='Resumo')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(config_name='extends', verbose_name='Conteúdo Completo')),
                ('featured_image', models.ImageField(help_text='Imagem principal do artigo (recomendado: 1200x630px)', upload_to='news/featured/', verbose_name='Imagem de Destaque')),
                ('image_caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda da Imagem')),
                ('video_url', models.URLField(blank=True, help_text='URL do YouTube ou Vimeo (opcional)', verbose_name='URL do Vídeo')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Destaque Principal')], default=2, verbose_name='Prioridade')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparecer em destaque na página principal', verbose_name='Destaque na Home')),
                ('is_breaking', models.BooleanField(default=False, help_text="Badge especial de 'ÚLTIMA HORA'", verbose_name='Notícia de Última Hora')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Evento')),
                ('event_location', models.CharField(blank=True, max_length=200, verbose_name='Local do Evento')),
                ('event_link', models.URLField(blank=True, help_text='Link para inscrição/mais informações', verbose_name='Link do Evento')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.book', verbose_name='Livro Relacionado')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Categoria')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Quiz')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('featured_image', models.ImageField(blank=True, upload_to='news/quizzes/', verbose_name='Imagem de Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('show_results_immediately', models.BooleanField(default=True, help_text='Mostrar resultado após cada resposta ou apenas no final', verbose_name='Mostrar Resultado Imediatamente')),
                ('times_completed', models.PositiveIntegerField(default=0, verbose_name='Vezes Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='news.category', verbose_name='Categoria')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='news.article', verbose_name='Artigo Relacionado')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, verbose_name='Pergunta')),
                ('question_image', models.ImageField(blank=True, upload_to='news/quiz_questions/', verbose_name='Imagem da Pergunta')),
                ('explanation', models.TextField(blank=True, help_text='Explicação mostrada após responder (opcional)', verbose_name='Explicação')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='news.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Pergunta do Quiz',
                'verbose_name_plural': 'Perguntas do Quiz',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='Opção')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Resposta Correta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='news.quizquestion', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_type', '-published_at'], name='news_articl_content_48bd61_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', '-published_at'], name='news_articl_is_feat_7be6d2_idx'),
        ),
    ]
