# Generated by Django 5.1.1 on 2025-12-09 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Pontuação (acertos)')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Total de Perguntas')),
                ('score_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Acertos')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP Ganho')),
                ('leveled_up', models.BooleanField(default=False, verbose_name='Subiu de Nível')),
                ('level_before', models.PositiveIntegerField(default=1, verbose_name='Nível Anterior')),
                ('level_after', models.PositiveIntegerField(default=1, verbose_name='Nível Após')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completado em')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='news.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='news_quizat_user_id_485b8f_idx'), models.Index(fields=['quiz', '-completed_at'], name='news_quizat_quiz_id_4be47a_idx')],
            },
        ),
    ]
