# Generated by Django 5.1.1 on 2025-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Fonte')),
                ('url', models.URLField(unique=True, verbose_name='URL do Feed')),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('atom', 'Atom Feed'), ('json', 'JSON Feed')], default='rss', max_length=10, verbose_name='Tipo de Feed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('priority', models.IntegerField(default=5, help_text='1-10, quanto maior mais importante', verbose_name='Prioridade')),
                ('keywords_include', models.JSONField(blank=True, default=list, help_text='Notícias devem conter pelo menos uma dessas palavras', verbose_name='Palavras-chave (incluir)')),
                ('keywords_exclude', models.JSONField(blank=True, default=list, help_text='Notícias com essas palavras serão ignoradas', verbose_name='Palavras-chave (excluir)')),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Busca')),
                ('last_fetch_status', models.CharField(blank=True, max_length=50, verbose_name='Status da Última Busca')),
                ('total_items_fetched', models.IntegerField(default=0, verbose_name='Total de Itens Buscados')),
                ('total_items_published', models.IntegerField(default=0, verbose_name='Total de Itens Publicados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fonte de Notícias',
                'verbose_name_plural': 'Fontes de Notícias',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Indica se o artigo foi gerado automaticamente por IA', verbose_name='Gerado por IA'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Ex: gemini-pro, gemini-1.5-flash', max_length=50, verbose_name='Modelo IA'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo de Processamento (segundos)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição para mecanismos de busca (máx 160 caracteres)', max_length=160, verbose_name='Meta Descrição (SEO)'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da Fonte'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link para a notícia original', verbose_name='URL da Fonte Original'),
        ),
    ]
