# Generated by Django 5.1.1 on 2025-12-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_add_newssource_and_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuração Principal', max_length=100, verbose_name='Nome da Configuração')),
                ('mode', models.CharField(choices=[('manual', '🔧 Manual'), ('automatic', '🤖 Automático'), ('paused', '⏸️ Pausado')], default='manual', max_length=20, verbose_name='Modo de Operação')),
                ('is_active', models.BooleanField(default=True, help_text='Apenas uma configuração pode estar ativa', verbose_name='Configuração Ativa')),
                ('articles_per_run', models.PositiveIntegerField(default=5, help_text='Quantos artigos gerar por vez', verbose_name='Artigos por Execução')),
                ('hours_lookback', models.PositiveIntegerField(default=24, help_text='Buscar notícias das últimas X horas', verbose_name='Período de Busca (horas)')),
                ('include_images', models.BooleanField(default=True, help_text='Buscar imagens do Unsplash para os artigos', verbose_name='Incluir Imagens')),
                ('schedule', models.CharField(choices=[('hourly', 'A cada hora'), ('every_6h', 'A cada 6 horas'), ('every_12h', 'A cada 12 horas'), ('daily', 'Diário'), ('twice_daily', '2x ao dia'), ('weekly', 'Semanal')], default='daily', max_length=20, verbose_name='Frequência')),
                ('schedule_hour', models.PositiveIntegerField(default=6, help_text='Hora do dia para execução automática (0-23)', verbose_name='Horário (hora)')),
                ('schedule_minute', models.PositiveIntegerField(default=0, help_text='Minuto da hora (0-59)', verbose_name='Horário (minuto)')),
                ('specific_themes', models.TextField(blank=True, help_text='Um tema por linha. Ex: Stephen King, Tolkien, Manga', verbose_name='Temas Específicos')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('last_run_articles', models.PositiveIntegerField(default=0, verbose_name='Artigos na Última Execução')),
                ('total_articles_generated', models.PositiveIntegerField(default=0, verbose_name='Total de Artigos Gerados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_filter', models.ForeignKey(blank=True, help_text='Gerar artigos apenas para esta categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Filtrar por Categoria')),
            ],
            options={
                'verbose_name': '⚙️ Configuração do Agente',
                'verbose_name_plural': '⚙️ Configurações do Agente',
            },
        ),
    ]
