# Generated by Django 5.1.1 on 2025-12-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_news_agent_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoption',
            name='option_text',
            field=models.CharField(max_length=500, verbose_name='Opção'),
        ),
    ]
