# Generated by Django 6.0.6 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_video_related_book_video_related_books'),
        ('news', '0005_increase_quizoption_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_book',
        ),
        migrations.AddField(
            model_name='article',
            name='related_books',
            field=models.ManyToManyField(blank=True, help_text='Selecione um ou mais livros relacionados a este artigo', related_name='articles', to='core.book', verbose_name='Livros Relacionados'),
        ),
    ]
