# Generated by Django 6.0.6 on 2026-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_articlecomment_articlelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/quizzes/', verbose_name='Imagem de Capa do Quiz'),
        ),
    ]
