# Generated by Django 5.0.3 on 2025-09-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_author_bio_alter_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Título da seção (ex: 'Mais Vendidos', 'Lançamentos')", max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Texto descritivo opcional', max_length=200, verbose_name='Subtítulo')),
                ('content_type', models.CharField(choices=[('books', 'Livros'), ('authors', 'Autores'), ('videos', 'Vídeos'), ('mixed', 'Misto')], default='books', max_length=20, verbose_name='Tipo de Conteúdo')),
                ('layout', models.CharField(choices=[('carousel', 'Carrossel'), ('grid', 'Grid'), ('list', 'Lista'), ('featured', 'Destaque Grande')], default='carousel', max_length=20, verbose_name='Layout de Exibição')),
                ('active', models.BooleanField(default=True, help_text='Seção será exibida na home', verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor = aparece primeiro)', verbose_name='Ordem')),
                ('background_color', models.CharField(blank=True, help_text='Ex: #f8f9fa, transparent', max_length=20, verbose_name='Cor de Fundo')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='Classe CSS Personalizada')),
                ('items_per_row', models.PositiveIntegerField(default=4, help_text='Aplicável para layout grid e carousel', verbose_name='Itens por Linha')),
                ('show_see_more', models.BooleanField(default=True, help_text='Exibir link para ver todos os itens', verbose_name="Mostrar 'Ver Mais'")),
                ('see_more_url', models.CharField(blank=True, help_text='Ex: /livros/?categoria=lancamentos', max_length=200, verbose_name="URL do 'Ver Mais'")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do vídeo', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descrição do conteúdo do vídeo', verbose_name='Descrição')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], default='youtube', max_length=20, verbose_name='Plataforma')),
                ('video_url', models.URLField(help_text='URL completa do vídeo (ex: https://www.youtube.com/watch?v=...)', verbose_name='URL do Vídeo')),
                ('embed_code', models.CharField(blank=True, help_text='ID do vídeo para embed (ex: dQw4w9WgXcQ para YouTube)', max_length=100, verbose_name='Código de Embed')),
                ('video_type', models.CharField(choices=[('trailer', 'Book Trailer'), ('interview', 'Entrevista'), ('review', 'Resenha'), ('tutorial', 'Tutorial'), ('discussion', 'Discussão'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de Vídeo')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL da imagem de preview (gerada automaticamente para YouTube)', verbose_name='URL da Thumbnail')),
                ('duration', models.CharField(blank=True, help_text='Duração do vídeo (ex: 10:25)', max_length=20, verbose_name='Duração')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('featured', models.BooleanField(default=False, help_text='Vídeo será exibido em seções especiais', verbose_name='Destacado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('related_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.author', verbose_name='Autor Relacionado')),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.book', verbose_name='Livro Relacionado')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição dentro da seção', verbose_name='Ordem')),
                ('custom_title', models.CharField(blank=True, help_text='Se preenchido, sobrescreve o título original', max_length=200, verbose_name='Título Customizado')),
                ('custom_description', models.TextField(blank=True, verbose_name='Descrição Customizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('book', 'author', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.section', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Item da Seção',
                'verbose_name_plural': 'Itens das Seções',
                'ordering': ['order', '-created_at'],
                'unique_together': {('section', 'content_type', 'object_id')},
            },
        ),
    ]
