# Generated by Django 5.0.3 on 2025-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_section_video_sectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, help_text='Nome de usuário (sem @)', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do autor (recomendado: 400x400px)', null=True, upload_to='authors/photos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, help_text='Nome de usuário (sem @)', max_length=100, verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text='Site oficial do autor', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
