# Generated by Django 5.0.3 on 2025-09-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_instagram_author_photo_author_twitter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome do evento', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descrição completa do evento', verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, help_text='Resumo para o widget (gerado automaticamente se vazio)', max_length=200, verbose_name='Descrição Curta')),
                ('event_type', models.CharField(choices=[('launch', 'Lançamento de Livro'), ('fair', 'Feira Literária'), ('meetup', 'Encontro com Autor'), ('workshop', 'Workshop'), ('lecture', 'Palestra'), ('signing', 'Sessão de Autógrafos'), ('reading', 'Clube de Leitura'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de Evento')),
                ('banner_image', models.ImageField(help_text='Imagem grande para página do evento (recomendado: 1200x600px)', upload_to='events/banners/', verbose_name='Banner Principal')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Imagem pequena para cards (recomendado: 400x300px)', upload_to='events/thumbnails/', verbose_name='Thumbnail')),
                ('start_date', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data/Hora de Término')),
                ('location_name', models.CharField(help_text='Ex: Livraria Cultura Shopping Iguatemi', max_length=200, verbose_name='Nome do Local')),
                ('location_address', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('location_state', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('is_online', models.BooleanField(default=False, help_text='Marque se o evento for online/virtual', verbose_name='Evento Online')),
                ('event_url', models.URLField(help_text='URL da página oficial do evento', verbose_name='Link do Evento')),
                ('registration_url', models.URLField(blank=True, help_text='URL para inscrição/compra de ingressos', verbose_name='Link de Inscrição')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Número máximo de participantes', null=True, verbose_name='Capacidade')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco se for gratuito', max_digits=10, null=True, verbose_name='Preço')),
                ('is_free', models.BooleanField(default=True, verbose_name='Evento Gratuito')),
                ('featured', models.BooleanField(default=False, help_text='Evento será exibido em destaque', verbose_name='Destaque')),
                ('active', models.BooleanField(default=True, help_text='Desmarque para ocultar o evento', verbose_name='Ativo')),
                ('status', models.CharField(choices=[('upcoming', 'Próximo'), ('ongoing', 'Acontecendo'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='upcoming', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('related_authors', models.ManyToManyField(blank=True, related_name='events', to='core.author', verbose_name='Autores Participantes')),
                ('related_books', models.ManyToManyField(blank=True, help_text='Livros que serão lançados ou discutidos no evento', related_name='events', to='core.book', verbose_name='Livros Relacionados')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_date'],
            },
        ),
    ]
