# Generated by Django 6.0a1 on 2025-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='core_book_created_e8fd66_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='core_book_created_3b4e00_idx'),
        ),
    ]
