# Generated by Django 6.0a1 on 2025-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_book_core_book_created_e8fd66_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco se não houver preço definido', max_digits=10, null=True, verbose_name='Preço'),
        ),
    ]
