# Generated by Django 6.0a1 on 2025-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_make_price_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_partner_name',
            field=models.CharField(blank=True, help_text='Nome do parceiro onde o livro pode ser adquirido (ex: Amazon, Saraiva, Cultura)', max_length=100, verbose_name='Parceiro Comercial'),
        ),
        migrations.AddField(
            model_name='book',
            name='purchase_partner_url',
            field=models.URLField(blank=True, help_text='URL completa da página do livro no site do parceiro comercial', max_length=500, verbose_name='Link para Compra'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor médio de mercado (informativo)', max_digits=10, null=True, verbose_name='Preço Médio'),
        ),
    ]
