# Generated by Django 5.0.3 on 2025-11-02 13:43

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_purchase_partner_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do banner (para identificação no admin)', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Texto secundário exibido no banner (opcional)', max_length=200, verbose_name='Subtítulo')),
                ('description', models.TextField(blank=True, help_text='Texto descritivo exibido no banner (opcional)', verbose_name='Descrição')),
                ('image', models.ImageField(help_text='Imagem do banner (recomendado: 1920x600px, máx. 5MB)', storage=core.storage_backends.SupabaseMediaStorage(), upload_to='banners/home/', verbose_name='Imagem do Banner')),
                ('link_url', models.URLField(blank=True, help_text='URL para onde o usuário será direcionado ao clicar (opcional)', verbose_name='Link de Destino')),
                ('link_text', models.CharField(blank=True, default='Saiba mais', help_text='Texto exibido no botão de ação', max_length=50, verbose_name='Texto do Botão')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Marque para abrir o link em nova aba', verbose_name='Abrir em Nova Aba')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem em que o banner aparece no carrossel (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('active', models.BooleanField(default=True, help_text='Desmarque para ocultar este banner', verbose_name='Ativo')),
                ('start_date', models.DateTimeField(blank=True, help_text='Data/hora de início da exibição (deixe vazio para exibir imediatamente)', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, help_text='Data/hora de término da exibição (deixe vazio para exibir indefinidamente)', null=True, verbose_name='Data de Término')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Número de vezes que o banner foi exibido', verbose_name='Visualizações')),
                ('clicks_count', models.PositiveIntegerField(default=0, help_text='Número de cliques no banner', verbose_name='Cliques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
