# Generated by Django 5.1.1 on 2025-11-20 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_banner_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='container_opacity',
            field=models.FloatField(default=1.0, help_text='Transparência do container (0.0 = totalmente transparente, 1.0 = totalmente opaco)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Opacidade do Container'),
        ),
    ]
