# Generated by Django 5.1.1 on 2025-11-20 13:31

import django.core.validators
from django.db import migrations, models


def add_container_opacity_if_not_exists(apps, schema_editor):
    """
    Adiciona o campo container_opacity apenas se ele não existir.
    Compatível com PostgreSQL e SQLite.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        vendor = connection.vendor  # 'postgresql' ou 'sqlite'

        if vendor == 'sqlite':
            # SQLite: usa PRAGMA table_info
            cursor.execute("PRAGMA table_info(core_section);")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = 'container_opacity' in columns

            if not column_exists:
                cursor.execute("""
                    ALTER TABLE core_section
                    ADD COLUMN container_opacity REAL DEFAULT 1.0 NOT NULL;
                """)
                print("[OK] Coluna container_opacity criada com sucesso (SQLite)")
            else:
                print("[INFO] Coluna container_opacity ja existe, pulando criacao")

        else:
            # PostgreSQL: usa information_schema
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='core_section' AND column_name='container_opacity';
            """)

            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE core_section
                    ADD COLUMN container_opacity DOUBLE PRECISION DEFAULT 1.0 NOT NULL
                    CHECK (container_opacity >= 0.0 AND container_opacity <= 1.0);
                """)
                print("[OK] Coluna container_opacity criada com sucesso (PostgreSQL)")
            else:
                print("[INFO] Coluna container_opacity ja existe, pulando criacao")


def reverse_add_container_opacity(apps, schema_editor):
    """Remove o campo container_opacity se a migration for revertida"""
    from django.db import connection

    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            # SQLite não suporta DROP COLUMN diretamente em versões antigas
            # Mas versões mais novas (3.35+) suportam
            try:
                cursor.execute("ALTER TABLE core_section DROP COLUMN container_opacity;")
            except Exception:
                print("[WARN] SQLite nao suporta DROP COLUMN, ignorando")
        else:
            cursor.execute("ALTER TABLE core_section DROP COLUMN IF EXISTS container_opacity;")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_banner_height'),
    ]

    operations = [
        # Separa as operações de STATE (Django) e DATABASE (SQL)
        # Isso garante que o Django saiba que o campo existe (evita criar migration 0013)
        # mas só cria no banco se não existir (evita DuplicateColumn)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # STATE: Diz ao Django que o campo existe
                migrations.AddField(
                    model_name='section',
                    name='container_opacity',
                    field=models.FloatField(
                        default=1.0,
                        help_text='Transparência do container (0.0 = totalmente transparente, 1.0 = totalmente opaco)',
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0)
                        ],
                        verbose_name='Opacidade do Container'
                    ),
                ),
            ],
            database_operations=[
                # DATABASE: Só cria se não existir
                migrations.RunPython(
                    add_container_opacity_if_not_exists,
                    reverse_add_container_opacity
                ),
            ],
        ),
    ]
