# Generated by Django 5.1.1 on 2025-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_section_container_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='card_hover_effect',
            field=models.CharField(blank=True, choices=[('none', 'Nenhum'), ('scale', 'Aumentar'), ('lift', 'Elevar'), ('glow', 'Brilho'), ('tilt', 'Inclinação')], default='scale', help_text='Efeito de hover nos cards', max_length=50, verbose_name='Efeito ao Passar Mouse'),
        ),
        migrations.AddField(
            model_name='section',
            name='card_style',
            field=models.CharField(blank=True, choices=[('default', 'Padrão'), ('minimal', 'Minimalista'), ('shadow', 'Com Sombra'), ('bordered', 'Com Borda'), ('gradient', 'Com Gradiente'), ('overlay', 'Com Overlay')], default='default', help_text='Estilo visual dos cards nesta seção', max_length=50, verbose_name='Estilo do Card'),
        ),
        migrations.AddField(
            model_name='section',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS customizado para esta seção (será inserido dentro de uma tag <style>)', verbose_name='CSS Personalizado'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_author',
            field=models.BooleanField(default=True, help_text='Exibir nome do autor nos cards de livros', verbose_name='Mostrar Autor'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_price',
            field=models.BooleanField(default=True, help_text='Exibir preço nos cards de livros', verbose_name='Mostrar Preço'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_rating',
            field=models.BooleanField(default=True, help_text='Exibir estrelas de avaliação', verbose_name='Mostrar Avaliação'),
        ),
        migrations.AlterField(
            model_name='section',
            name='layout',
            field=models.CharField(choices=[('carousel', 'Carrossel'), ('grid', 'Grid'), ('list', 'Lista'), ('featured', 'Destaque Grande'), ('cards_large', 'Cards Grandes (2 colunas)'), ('cards_small', 'Cards Pequenos (6 colunas)'), ('banner_slider', 'Banner com Slider'), ('grid_masonry', 'Grid Masonry (Pinterest style)'), ('horizontal_scroll', 'Scroll Horizontal'), ('spotlight', 'Destaque com Overlay')], default='carousel', max_length=20, verbose_name='Layout de Exibição'),
        ),
    ]
