# Generated by Django 5.1.1 on 2025-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_section_container_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo ou banner promocional para a seção (recomendado: 1920x400px)', null=True, upload_to='sections/banners/', verbose_name='Imagem de Banner'),
        ),
    ]
