# Generated by Django 5.1.1 on 2025-11-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_custom_layouts_to_sections'),
        ('core', '0014_section_banner_image'),
    ]

    operations = [
    ]
