# Generated by Django 5.1.1 on 2025-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20251128_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='layout',
            field=models.CharField(choices=[('carousel', 'Carrossel'), ('grid', 'Grid'), ('list', 'Lista'), ('featured', 'Destaque Grande'), ('cards_large', 'Cards Grandes (2 colunas)'), ('cards_small', 'Cards Pequenos (6 colunas)'), ('banner_slider', 'Banner com Slider'), ('grid_masonry', 'Grid Masonry (Pinterest style)'), ('horizontal_scroll', 'Scroll Horizontal'), ('spotlight', 'Destaque com Overlay'), ('banner_only', 'Apenas Banner (sem itens)')], default='carousel', max_length=20, verbose_name='Layout de Exibição'),
        ),
    ]
