# Generated by Django 5.1.1 on 2025-12-04 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_section_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='banner_border_opacity',
            field=models.FloatField(default=0.0, help_text='Opacidade do efeito de borda/gradiente nas bordas do banner (0.0 = sem efeito, 1.0 = opaco)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Opacidade das Bordas'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_height',
            field=models.PositiveIntegerField(default=400, help_text='Altura do banner em pixels (padrão: 400px)', verbose_name='Altura do Banner (px)'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_opacity',
            field=models.FloatField(default=1.0, help_text='Opacidade da imagem do banner (0.0 = totalmente transparente, 1.0 = totalmente opaco)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Transparência do Banner'),
        ),
    ]
