# Generated by Django 5.1.1 on 2025-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_section_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Upload de thumbnail para Instagram, Vimeo, TikTok, etc.', null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail Customizada'),
        ),
    ]
