# Generated by Django 5.1.1 on 2025-12-05 12:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_banner_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título principal da crônica', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo ou chamada (opcional)', max_length=300, verbose_name='Subtítulo')),
                ('introduction', models.TextField(help_text='Texto introdutório da crônica', verbose_name='Introdução')),
                ('main_content', models.TextField(help_text='Conteúdo principal da crônica', verbose_name='Conteúdo Principal')),
                ('conclusion', models.TextField(blank=True, help_text='Texto de conclusão (opcional)', verbose_name='Conclusão')),
                ('author_name', models.CharField(default='Equipe CG.BookStore', help_text='Nome do autor da crônica', max_length=100, verbose_name='Autor')),
                ('quote', models.TextField(blank=True, help_text='Citação ou trecho em destaque (opcional)', verbose_name='Citação em Destaque')),
                ('quote_author', models.CharField(blank=True, help_text='Autor da citação em destaque (opcional)', max_length=100, verbose_name='Autor da Citação')),
                ('featured_image', models.ImageField(help_text='Imagem principal da crônica', upload_to='chronicles/featured/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem Principal')),
                ('featured_image_ratio', models.CharField(choices=[('1:1', 'Quadrado (1:1)'), ('4:5', 'Vertical (4:5)'), ('16:9', 'Horizontal (16:9)')], default='16:9', help_text='Proporção da imagem principal', max_length=10, verbose_name='Proporção da Imagem Principal')),
                ('secondary_image', models.ImageField(blank=True, help_text='Imagem secundária (opcional)', null=True, upload_to='chronicles/secondary/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem Secundária')),
                ('secondary_image_ratio', models.CharField(choices=[('1:1', 'Quadrado (1:1)'), ('4:5', 'Vertical (4:5)'), ('16:9', 'Horizontal (16:9)')], default='1:1', help_text='Proporção da imagem secundária', max_length=10, verbose_name='Proporção da Imagem Secundária')),
                ('gallery_image_1', models.ImageField(blank=True, help_text='Primeira imagem da galeria (opcional)', null=True, upload_to='chronicles/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Galeria - Imagem 1')),
                ('gallery_image_1_ratio', models.CharField(choices=[('1:1', 'Quadrado (1:1)'), ('4:5', 'Vertical (4:5)'), ('16:9', 'Horizontal (16:9)')], default='4:5', help_text='Proporção da primeira imagem da galeria', max_length=10, verbose_name='Proporção - Galeria 1')),
                ('gallery_image_2', models.ImageField(blank=True, help_text='Segunda imagem da galeria (opcional)', null=True, upload_to='chronicles/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Galeria - Imagem 2')),
                ('gallery_image_2_ratio', models.CharField(choices=[('1:1', 'Quadrado (1:1)'), ('4:5', 'Vertical (4:5)'), ('16:9', 'Horizontal (16:9)')], default='4:5', help_text='Proporção da segunda imagem da galeria', max_length=10, verbose_name='Proporção - Galeria 2')),
                ('gallery_image_3', models.ImageField(blank=True, help_text='Terceira imagem da galeria (opcional)', null=True, upload_to='chronicles/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Galeria - Imagem 3')),
                ('gallery_image_3_ratio', models.CharField(choices=[('1:1', 'Quadrado (1:1)'), ('4:5', 'Vertical (4:5)'), ('16:9', 'Horizontal (16:9)')], default='4:5', help_text='Proporção da terceira imagem da galeria', max_length=10, verbose_name='Proporção - Galeria 3')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de publicação da crônica', verbose_name='Data de Publicação')),
                ('is_published', models.BooleanField(default=True, help_text='Marque para publicar a crônica', verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para SEO (opcional, máx. 160 caracteres)', max_length=160, verbose_name='Meta Descrição')),
            ],
            options={
                'verbose_name': 'Crônica Semanal',
                'verbose_name_plural': 'Crônicas Semanais',
                'ordering': ['-published_date'],
            },
        ),
    ]
