# Generated by Django 5.1.1 on 2025-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_update_chronicle_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Upload de thumbnail para vídeos não-YouTube (Instagram, Vimeo, TikTok, etc.)', null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail Customizada'),
        ),
    ]
