# Generated by Django 5.1.1 on 2025-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_video_thumbnail_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyChronicle',
        ),
        migrations.RemoveField(
            model_name='section',
            name='banner_border_opacity',
        ),
        migrations.RemoveField(
            model_name='section',
            name='banner_height',
        ),
        migrations.RemoveField(
            model_name='section',
            name='banner_opacity',
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL para onde o usuário será direcionado ao clicar. Ex: /novos-autores/ ou https://site.com', max_length=500, verbose_name='Link de Destino'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Upload de thumbnail para Instagram, Vimeo, TikTok, etc.', null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail Customizada'),
        ),
    ]
