# Generated by Django 5.1.1 on 2025-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_weeklychronicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='blur_edges',
            field=models.BooleanField(default=True, help_text='Aplica efeito de desfoque gradual nas bordas superior e inferior do banner', verbose_name='Desfocar Bordas'),
        ),
        migrations.AddField(
            model_name='banner',
            name='blur_intensity',
            field=models.PositiveIntegerField(default=100, help_text='Tamanho da área de desfoque nas bordas (recomendado: 80-150px)', verbose_name='Intensidade do Desfoque (px)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_position_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Onde a imagem deve ser posicionada horizontalmente no banner', max_length=10, verbose_name='Posição Horizontal da Imagem'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_position_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Inferior')], default='center', help_text='Onde a imagem deve ser posicionada verticalmente no banner', max_length=10, verbose_name='Posição Vertical da Imagem'),
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_opacity',
            field=models.FloatField(default=0.3, help_text='Escurecimento sobre a imagem (0.0 = transparente, 1.0 = totalmente escuro). Recomendado: 0.2-0.4', verbose_name='Opacidade do Overlay Escuro'),
        ),
    ]
