# Generated by Django 5.1.1 on 2025-12-09 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_banner_blur_edges_banner_blur_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='banner_blur_edges',
            field=models.BooleanField(default=False, help_text='Aplica desfoque gradual nas bordas superior e inferior do banner', verbose_name='Desfocar Bordas do Banner'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_blur_intensity',
            field=models.PositiveIntegerField(default=80, help_text='Tamanho da área de desfoque nas bordas (recomendado: 60-120px)', verbose_name='Intensidade do Desfoque do Banner (px)'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_height',
            field=models.PositiveIntegerField(default=400, help_text='Altura do banner em pixels (padrão: 400px, recomendado: 300-500px)', verbose_name='Altura do Banner (px)'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_overlay_opacity',
            field=models.FloatField(default=0.5, help_text='Escurecimento sobre a imagem do banner (0.0-1.0, recomendado: 0.4-0.6)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Opacidade do Overlay do Banner'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_position_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Onde a imagem do banner deve ser posicionada horizontalmente', max_length=10, verbose_name='Posição Horizontal do Banner'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_position_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Inferior')], default='center', help_text='Onde a imagem do banner deve ser posicionada verticalmente', max_length=10, verbose_name='Posição Vertical do Banner'),
        ),
    ]
