# Generated by Django 5.1.1 on 2025-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_section_banner_blur_edges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, help_text="Título da seção (ex: 'Mais Vendidos', 'Lançamentos'). Deixe vazio para seções apenas com banner.", max_length=200, verbose_name='Título'),
        ),
    ]
