# Generated by Django 5.1.1 on 2025-12-14 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload de arquivo MP4 ou WebM (máx. 100MB recomendado)', null=True, upload_to='videos/uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi'])], verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('upload', 'Upload de Arquivo')], default='youtube', max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL completa do vídeo (para YouTube, Vimeo, Instagram, TikTok)', verbose_name='URL do Vídeo'),
        ),
    ]
