# Generated by Django 5.1.1 on 2025-12-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_video_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedAuthorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Se marcado, a seção será exibida na home', verbose_name='Ativo')),
                ('home_title', models.CharField(default='Mundo de Tolkien', help_text='Título principal da seção (ex: "Mundo de Tolkien")', max_length=100, verbose_name='Título na Home')),
                ('home_subtitle', models.CharField(default='Explore o Mundo de', help_text='Texto acima do título (ex: "Explore o Mundo de")', max_length=100, verbose_name='Subtítulo')),
                ('home_description', models.TextField(default='Descubra a Terra-média através das obras do mestre da fantasia', help_text='Descrição exibida na seção da home', verbose_name='Descrição Curta')),
                ('home_banner_image', models.ImageField(blank=True, help_text='Imagem de fundo da seção (recomendado: 1920x600px)', null=True, upload_to='featured_authors/banners/', verbose_name='Banner da Seção')),
                ('home_button_text', models.CharField(default='Explorar Mundo de Tolkien', help_text='Texto exibido no botão de ação', max_length=50, verbose_name='Texto do Botão')),
                ('home_button_icon', models.CharField(default='fa-compass', help_text='Classe Font Awesome (ex: fa-compass, fa-book)', max_length=50, verbose_name='Ícone do Botão')),
                ('page_title', models.CharField(default='Explore o Mundo de J.R.R. Tolkien', help_text='Título exibido na página dedicada', max_length=200, verbose_name='Título da Página')),
                ('page_description', models.TextField(default='Mergulhe nas obras do mestre da fantasia que criou a Terra-média e encantou gerações de leitores.', help_text='Descrição longa exibida na página', verbose_name='Descrição da Página')),
                ('page_meta_title', models.CharField(blank=True, help_text='Título para SEO (máx 70 caracteres)', max_length=70, verbose_name='Meta Title (SEO)')),
                ('page_meta_description', models.CharField(blank=True, help_text='Descrição para SEO (máx 160 caracteres)', max_length=160, verbose_name='Meta Description (SEO)')),
                ('stat_badge_1', models.CharField(blank=True, default='Épicos', help_text='Primeiro badge/rótulo de estatística', max_length=30, verbose_name='Badge 1')),
                ('stat_badge_2', models.CharField(blank=True, default='Lendários', help_text='Segundo badge/rótulo de estatística', max_length=30, verbose_name='Badge 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(help_text='Selecione o autor em destaque', on_delete=django.db.models.deletion.CASCADE, related_name='featured_settings', to='core.author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Autor em Destaque',
                'verbose_name_plural': 'Autores em Destaque',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
