# Generated by Django 5.1.1 on 2026-01-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_change_author_on_delete_to_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do universo (ex: "Mundo de Tolkien")', max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Identificador na URL (ex: tolkien -> /universo/tolkien/)', unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, a página será acessível', verbose_name='Ativo')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Usado para ordenar na listagem', verbose_name='Ordem de Exibição')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Exibir link no menu principal', verbose_name='Mostrar no Menu')),
                ('theme_color_primary', models.CharField(default='#f4d03f', help_text='Cor em hexadecimal (ex: #f4d03f)', max_length=7, verbose_name='Cor Primária')),
                ('theme_color_secondary', models.CharField(default='#c9a227', help_text='Cor secundária em hexadecimal', max_length=7, verbose_name='Cor Secundária')),
                ('hero_icon', models.CharField(default='fa-ring', help_text='Classe Font Awesome (ex: fa-ring, fa-dragon)', max_length=50, verbose_name='Ícone do Hero')),
                ('hero_banner_image', models.ImageField(blank=True, help_text='Imagem de fundo do hero (recomendado: 1920x600)', null=True, upload_to='literary_universes/banners/', verbose_name='Banner do Hero')),
                ('books_card_style', models.CharField(choices=[('default', 'Padrão'), ('compact', 'Compacto'), ('expanded', 'Expandido'), ('minimal', 'Minimalista')], default='default', max_length=20, verbose_name='Estilo Cards de Livros')),
                ('books_container_style', models.CharField(choices=[('grid', 'Grid (padrão)'), ('carousel', 'Carrossel'), ('masonry', 'Masonry'), ('list', 'Lista')], default='grid', max_length=20, verbose_name='Container de Livros')),
                ('articles_card_style', models.CharField(choices=[('default', 'Padrão'), ('compact', 'Compacto'), ('expanded', 'Expandido'), ('minimal', 'Minimalista')], default='default', max_length=20, verbose_name='Estilo Cards de Artigos')),
                ('articles_container_style', models.CharField(choices=[('grid', 'Grid (padrão)'), ('carousel', 'Carrossel'), ('masonry', 'Masonry'), ('list', 'Lista')], default='grid', max_length=20, verbose_name='Container de Artigos')),
                ('videos_card_style', models.CharField(choices=[('default', 'Padrão'), ('compact', 'Compacto'), ('expanded', 'Expandido'), ('minimal', 'Minimalista')], default='default', max_length=20, verbose_name='Estilo Cards de Vídeos')),
                ('videos_container_style', models.CharField(choices=[('grid', 'Grid (padrão)'), ('carousel', 'Carrossel'), ('masonry', 'Masonry'), ('list', 'Lista')], default='grid', max_length=20, verbose_name='Container de Vídeos')),
                ('content_card_style', models.CharField(choices=[('default', 'Padrão'), ('compact', 'Compacto'), ('expanded', 'Expandido'), ('minimal', 'Minimalista')], default='default', max_length=20, verbose_name='Estilo Cards de Conteúdo')),
                ('content_container_style', models.CharField(choices=[('grid', 'Grid (padrão)'), ('carousel', 'Carrossel'), ('masonry', 'Masonry'), ('list', 'Lista')], default='grid', max_length=20, verbose_name='Container de Conteúdo')),
                ('page_title', models.CharField(help_text='Título exibido no hero da página', max_length=200, verbose_name='Título da Página')),
                ('page_subtitle', models.CharField(default='Explore o Mundo de', help_text='Texto acima do título principal', max_length=100, verbose_name='Subtítulo')),
                ('page_description', models.TextField(help_text='Descrição exibida abaixo do título', verbose_name='Descrição da Página')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO (máx 70 caracteres)', max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para SEO (máx 160 caracteres)', max_length=160, verbose_name='Meta Description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(help_text='Autor principal deste universo', on_delete=django.db.models.deletion.CASCADE, related_name='literary_universes', to='core.author', verbose_name='Autor')),
                ('videos', models.ManyToManyField(blank=True, help_text='Vídeos relacionados a este universo', related_name='literary_universes', to='core.video', verbose_name='Vídeos Associados')),
            ],
            options={
                'verbose_name': 'Universo Literário',
                'verbose_name_plural': 'Universos Literários',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UniverseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Identificação no admin', max_length=100, verbose_name='Título (interno)')),
                ('image', models.ImageField(upload_to='literary_universes/banners/', verbose_name='Imagem Desktop')),
                ('image_mobile', models.ImageField(blank=True, help_text='Versão otimizada para dispositivos móveis', null=True, upload_to='literary_universes/banners/', verbose_name='Imagem Mobile')),
                ('alt_text', models.CharField(help_text='Descrição para acessibilidade', max_length=200, verbose_name='Texto Alternativo')),
                ('link_url', models.URLField(blank=True, help_text='Link ao clicar no banner', verbose_name='URL do Link')),
                ('link_target', models.CharField(choices=[('_self', 'Mesma aba'), ('_blank', 'Nova aba')], default='_self', max_length=20, verbose_name='Abrir em')),
                ('position', models.CharField(choices=[('after_hero', 'Após o Hero'), ('before_books', 'Antes dos Livros'), ('after_books', 'Após os Livros'), ('before_articles', 'Antes dos Artigos'), ('after_articles', 'Após os Artigos'), ('before_videos', 'Antes dos Vídeos'), ('after_videos', 'Após os Vídeos'), ('footer', 'Rodapé da Página')], default='after_hero', max_length=20, verbose_name='Posição na Página')),
                ('size', models.CharField(choices=[('full', 'Largura Total'), ('large', 'Grande (3/4)'), ('medium', 'Médio (2/3)'), ('small', 'Pequeno (1/2)')], default='full', max_length=20, verbose_name='Tamanho')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Para múltiplos banners na mesma posição', verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('start_date', models.DateTimeField(blank=True, help_text='Deixe em branco para exibir imediatamente', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, help_text='Deixe em branco para exibir indefinidamente', null=True, verbose_name='Data de Fim')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.literaryuniverse', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Banner do Universo',
                'verbose_name_plural': 'Banners do Universo',
                'ordering': ['position', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UniverseContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('game', 'Game'), ('adaptation', 'Adaptação (Filme/Série)'), ('podcast', 'Podcast'), ('article', 'Artigo Externo'), ('merchandise', 'Merchandise'), ('event', 'Evento'), ('link', 'Link Externo')], max_length=20, verbose_name='Tipo de Conteúdo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='literary_universes/content/', verbose_name='Thumbnail')),
                ('url', models.URLField(blank=True, help_text='Link externo (site oficial, loja, etc.)', verbose_name='URL')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('platform', models.CharField(blank=True, help_text='Ex: PC, PS5, Xbox, etc. (para games)', max_length=100, verbose_name='Plataforma')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='core.literaryuniverse', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Item de Conteúdo',
                'verbose_name_plural': 'Itens de Conteúdo',
                'ordering': ['content_type', 'display_order'],
            },
        ),
    ]
