# Generated by Django 5.1.1 on 2026-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_change_author_on_delete_to_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN-13 (ex: 978-0394534435) ou ISBN-10', max_length=14, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
