# Generated by Django 5.1.1 on 2026-01-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_literary_universe'),
        ('core', '0028_update_isbn_max_length'),
    ]

    operations = [
    ]
