# Generated by Django 5.1.1 on 2026-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20260116_0601'),
        ('news', '0005_increase_quizoption_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaryuniverse',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='Artigos/notícias relacionados a este universo (além da busca automática por tag)', related_name='literary_universes', to='news.article', verbose_name='Artigos Associados'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='hero_banner_overlay_opacity',
            field=models.FloatField(default=0.5, help_text='0.0 = totalmente transparente, 1.0 = totalmente escuro (recomendado: 0.3-0.6)', verbose_name='Opacidade do Overlay'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='hero_banner_position_horizontal',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Onde a imagem deve ser posicionada horizontalmente', max_length=10, verbose_name='Posição Horizontal do Banner'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='hero_banner_position_vertical',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Inferior')], default='center', help_text='Onde a imagem deve ser posicionada verticalmente', max_length=10, verbose_name='Posição Vertical do Banner'),
        ),
    ]
