# Generated by Django 5.1.1 on 2026-01-20 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_universe_banner_position_and_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='container_background_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo para o container da seção (aparece atrás dos cards)', null=True, upload_to='sections/backgrounds/', verbose_name='Imagem de Fundo do Container'),
        ),
        migrations.AddField(
            model_name='section',
            name='container_background_image_opacity',
            field=models.FloatField(default=0.3, help_text='Transparência da imagem de fundo (0.0 = invisível, 1.0 = totalmente visível). Recomendado: 0.2-0.5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Opacidade da Imagem de Fundo'),
        ),
        migrations.AddField(
            model_name='section',
            name='container_background_position',
            field=models.CharField(choices=[('center center', 'Centro'), ('top center', 'Topo'), ('bottom center', 'Inferior'), ('left center', 'Esquerda'), ('right center', 'Direita')], default='center center', help_text='Posição da imagem de fundo no container', max_length=20, verbose_name='Posição da Imagem de Fundo'),
        ),
        migrations.AddField(
            model_name='section',
            name='container_background_size',
            field=models.CharField(choices=[('cover', 'Cobrir (Cover)'), ('contain', 'Conter (Contain)'), ('auto', 'Automático')], default='cover', help_text='Como a imagem de fundo deve ser dimensionada', max_length=20, verbose_name='Tamanho da Imagem de Fundo'),
        ),
    ]
