# Generated by Django 5.1.1 on 2026-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_video_cards_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo para o container da seção (recomendado: 1920x600px)', null=True, upload_to='sections/backgrounds/', verbose_name='Imagem de Background'),
        ),
    ]
