# Generated by Django 5.1.1 on 2026-02-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0033_section_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('books', 'Livros'), ('authors', 'Autores'), ('videos', 'Vídeos'), ('news', 'Notícias'), ('mixed', 'Misto')], default='books', max_length=20, verbose_name='Tipo de Conteúdo'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('book', 'author', 'video', 'article')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo'),
        ),
    ]
