# Generated by Django 5.1.1 on 2026-03-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_section_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='background_image',
        ),
    ]
