# Generated by Django 5.1.1 on 2026-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_section_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_audiobook',
            field=models.BooleanField(default=False, help_text='Marque se o livro está disponível no formato Audiolivro', verbose_name='Disponível em Audiolivro'),
        ),
        migrations.AddField(
            model_name='book',
            name='available_kindle',
            field=models.BooleanField(default=False, help_text='Marque se o livro está disponível no formato Kindle/eBook', verbose_name='Disponível em Kindle'),
        ),
        migrations.AddField(
            model_name='book',
            name='available_pdf',
            field=models.BooleanField(default=False, help_text='Marque se o livro está disponível no formato PDF', verbose_name='Disponível em PDF'),
        ),
        migrations.AddField(
            model_name='book',
            name='available_print',
            field=models.BooleanField(default=False, help_text='Marque se o livro está disponível no formato impresso', verbose_name='Disponível em Livro Físico'),
        ),
    ]
