# Generated by Django 5.1.1 on 2026-04-02 13:21

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_reading_format_fields_to_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video_file',
            field=models.FileField(blank=True, help_text='Selecione um arquivo de vídeo (preferencialmente MP4, curtos e leves, sem áudio). Ele substituirá a imagem como fundo animado.', null=True, storage=core.storage_backends.SupabaseMediaStorage(), upload_to='banners/home/videos/', verbose_name='Vídeo do Banner (MP4)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do banner (recomendado: 1920x600px, máx. 5MB). Usado como fallback se não houver vídeo.', null=True, storage=core.storage_backends.SupabaseMediaStorage(), upload_to='banners/home/', verbose_name='Imagem do Banner'),
        ),
    ]
