# Generated by Django 5.1.1 on 2026-04-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_video_file_to_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Ex: 2024 ou 2023–2024', max_length=20, verbose_name='Ano (BR)')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('format', models.CharField(default='Capa comum', help_text='Ex: Capa comum, E-book, HQ, etc.', max_length=100, verbose_name='Formato')),
                ('publisher', models.CharField(blank=True, help_text='Ex: CG.BookStore / Amazon BR', max_length=200, verbose_name='Editora / Loja')),
                ('notes', models.TextField(blank=True, help_text='Informações adicionais sobre esta edição/obra', verbose_name='Observações')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controla a ordenação na tabela (menor = primeiro)', verbose_name='Ordem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Obra do Autor',
                'verbose_name_plural': 'Obras do Autor',
                'ordering': ['order', 'year', 'title'],
            },
        ),
    ]
