# Generated by Django 5.1.1 on 2026-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_presale_fields_to_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='highlight_message',
            field=models.TextField(blank=True, help_text="Texto que aparecerá no topo da página de detalhes (ex: 'Participe do evento com o autor!')", null=True, verbose_name='Mensagem de Destaque'),
        ),
        migrations.AddField(
            model_name='book',
            name='show_highlight',
            field=models.BooleanField(default=False, help_text='Se marcado, exibirá uma mensagem personalizada em destaque na cor verde.', verbose_name='Exibir Mensagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='book',
            name='presale_info',
            field=models.CharField(blank=True, help_text="Texto de destaque exibido na página do livro (ex: 'Garanta já o seu exemplar antes do lançamento!')", max_length=300, verbose_name='Mensagem de Pré-Venda'),
        ),
    ]
