# Generated by Django 5.1.1 on 2026-05-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_book_highlight_message_book_show_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('trailer', 'Book Trailer'), ('adaptation', 'Adaptação (Filme/Série/Anime)'), ('game', 'Game'), ('review', 'Resenha'), ('interview', 'Entrevista'), ('tutorial', 'Tutorial'), ('discussion', 'Discussão'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de Vídeo'),
        ),
    ]
