# Generated by Django 5.1.1 on 2026-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_adaptation_game_video_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_items',
            field=models.PositiveIntegerField(default=6, help_text='Número máximo de itens exibidos na seção. Usado pela rotação automática de notícias: quando uma nova notícia é publicada, ela entra no início e o card mais antigo é removido se este limite for atingido.', verbose_name='Máximo de Itens (Notícias)'),
        ),
    ]
