# Generated by Django 5.1.1 on 2026-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_max_items_to_section'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='core_book_title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_date'], name='core_book_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_presale'], name='core_book_presale_idx'),
        ),
    ]
