# Generated by Django 5.1.1 on 2026-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_book_indexes_for_admin_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaryuniverse',
            name='hero_icon',
            field=models.CharField(blank=True, default='fa-ring', help_text='Classe Font Awesome (ex: fa-ring, fa-dragon). Deixe em branco se não quiser nenhum ícone.', max_length=50, verbose_name='Ícone do Hero'),
        ),
    ]
