# Generated by Django 5.1.1 on 2026-06-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_literaryuniverse_hero_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredauthorsettings',
            name='page_banner_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo da página dedicada (recomendado: 1920x600px). Se não fornecido, usará o banner da home.', null=True, upload_to='featured_authors/banners/', verbose_name='Banner da Página Dedicada'),
        ),
    ]
