# Generated by Django 5.1.1 on 2026-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_featuredauthorsettings_page_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='layout',
            field=models.CharField(choices=[('carousel', 'Carrossel'), ('grid', 'Grid'), ('list', 'Lista'), ('featured', 'Destaque Grande'), ('cards_large', 'Cards Grandes (2 colunas)'), ('cards_small', 'Cards Pequenos (6 colunas)'), ('banner_slider', 'Banner com Slider'), ('grid_masonry', 'Grid Masonry (Pinterest style)'), ('horizontal_scroll', 'Scroll Horizontal'), ('spotlight', 'Destaque com Overlay'), ('banner_only', 'Apenas Banner (sem itens)'), ('video_cards', 'Cards de Vídeo com Preview (YouTube style)'), ('featured_author', 'Autor em Destaque (Tolkien)')], default='carousel', max_length=20, verbose_name='Layout de Exibição'),
        ),
    ]
