# Generated by Django 6.0.6 on 2026-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_section_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_expanded_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Análise Expandida de IA (JSON)'),
        ),
        migrations.AddField(
            model_name='book',
            name='ai_review',
            field=models.JSONField(blank=True, null=True, verbose_name='Análise de IA (JSON)'),
        ),
    ]
