# Generated by Django 6.0.6 on 2026-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_book_ai_expanded_analysis_book_ai_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL da imagem de preview (gerada automaticamente para YouTube)', max_length=500, verbose_name='URL da Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL completa do vídeo (para YouTube, Vimeo, Instagram, TikTok)', max_length=500, verbose_name='URL do Vídeo'),
        ),
    ]
