# Generated by Django 6.0.6 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_video_slug_alter_video_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='related_book',
        ),
        migrations.AddField(
            model_name='video',
            name='related_books',
            field=models.ManyToManyField(blank=True, help_text='Selecione um ou mais livros relacionados a este vídeo', related_name='videos', to='core.book', verbose_name='Livros Relacionados'),
        ),
    ]
