# Generated by Django 6.0.6 on 2026-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_deduplicate_existing_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='carousel_autoplay',
            field=models.BooleanField(default=False, help_text='Mover os itens do carrossel automaticamente sem precisar clicar', verbose_name='Carrossel Automático (Autoplay)'),
        ),
        migrations.AddField(
            model_name='section',
            name='carousel_autoplay_delay',
            field=models.PositiveIntegerField(default=4000, help_text='Tempo em milissegundos entre cada transição automática (ex: 3000 = 3s, 4000 = 4s, 5000 = 5s)', verbose_name='Velocidade do Autoplay (ms)'),
        ),
    ]
