# Generated by Django 6.0.6 on 2026-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_section_carousel_autoplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Cor do título, subtítulo e descrição sobre a imagem (ex: #ffffff, #f4d03f, #000000)', max_length=20, verbose_name='Cor dos Textos'),
        ),
        migrations.AddField(
            model_name='featuredauthorsettings',
            name='home_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Cor do título, subtítulo e descrição sobre o banner na home (ex: #ffffff, #f4d03f, #000000)', max_length=20, verbose_name='Cor dos Textos na Home'),
        ),
        migrations.AddField(
            model_name='section',
            name='banner_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Cor do título e subtítulo sobre o banner (ex: #ffffff, #f4d03f, #000000)', max_length=20, verbose_name='Cor dos Textos do Banner'),
        ),
    ]
