# Generated by Django 6.0.6 on 2026-08-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_banner_text_color_and_more'),
        ('news', '0007_articlecomment_articlelike'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: "Fantasia Épica", "Ficção Científica", "Mangás"', max_length=100, unique=True, verbose_name='Nome da Coleção')),
                ('slug', models.SlugField(help_text='Identificador na URL', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Classe Font Awesome (ex: fa-dragon, fa-rocket)', max_length=50, verbose_name='Ícone')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='literary_universes/collections/', verbose_name='Imagem de Capa')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Coleção de Universos',
                'verbose_name_plural': 'Coleções de Universos',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='additional_authors',
            field=models.ManyToManyField(blank=True, help_text='Outros autores deste universo (ex: Brandon Sanderson em A Roda do Tempo)', related_name='literary_universes_additional', to='core.author', verbose_name='Autores Adicionais'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='books',
            field=models.ManyToManyField(blank=True, help_text='Livros que pertencem a este universo (combinados automaticamente com os do autor principal)', related_name='literary_universes', to='core.book', verbose_name='Livros do Universo'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='URL canônica personalizada (deixe em branco para usar a URL padrão)', verbose_name='URL Canônica'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='featured_on_home',
            field=models.BooleanField(default=False, help_text='Se marcado, o universo poderá aparecer em destaque na página inicial', verbose_name='Destaque na Home'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logotipo ou imagem de identidade do universo (recomendado: 400x400)', null=True, upload_to='literary_universes/logos/', verbose_name='Logo do Universo'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='og_description',
            field=models.CharField(blank=True, help_text='Descrição para compartilhamento em redes sociais', max_length=200, verbose_name='Descrição Open Graph'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Imagem para compartilhamento em redes sociais (recomendado: 1200x630)', null=True, upload_to='literary_universes/og/', verbose_name='Imagem Open Graph'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='og_title',
            field=models.CharField(blank=True, help_text='Título para compartilhamento em redes sociais (máx 95 caracteres)', max_length=95, verbose_name='Título Open Graph'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='quizzes',
            field=models.ManyToManyField(blank=True, help_text='Quizzes e testes interativos relacionados a este universo', related_name='literary_universes', to='news.quiz', verbose_name='Quizzes Associados'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='related_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias de livros associadas a este universo', related_name='literary_universes', to='core.category', verbose_name='Categorias Relacionadas'),
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='related_universes',
            field=models.ManyToManyField(blank=True, help_text='Outros universos literários semelhantes para cross-linking', to='core.literaryuniverse', verbose_name='Universos Relacionados'),
        ),
        migrations.AddField(
            model_name='universecontentitem',
            name='media_status',
            field=models.CharField(blank=True, choices=[('released', '✅ Lançado'), ('in_production', '🎬 Em Produção'), ('announced', '📢 Anunciado'), ('rumored', '💬 Rumores'), ('cancelled', '❌ Cancelado')], help_text='Status atual da produção', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='universecontentitem',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, help_text='Número de temporadas (séries) ou volumes (HQs)', null=True, verbose_name='Temporadas / Volumes'),
        ),
        migrations.AddField(
            model_name='universecontentitem',
            name='studio',
            field=models.CharField(blank=True, help_text='Ex: Amazon Studios, Warner Bros, CD Projekt RED', max_length=200, verbose_name='Estúdio / Produtora'),
        ),
        migrations.AddField(
            model_name='universecontentitem',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Ano de lançamento ou estreia', null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='literaryuniverse',
            name='author',
            field=models.ForeignKey(help_text='Autor principal deste universo', on_delete=django.db.models.deletion.CASCADE, related_name='literary_universes', to='core.author', verbose_name='Autor Principal'),
        ),
        migrations.AlterField(
            model_name='universecontentitem',
            name='content_type',
            field=models.CharField(choices=[('game', '🎮 Game'), ('adaptation', '🎬 Adaptação (Filme/Série)'), ('anime', '🎌 Anime'), ('hq', '📚 HQ / Quadrinhos'), ('podcast', '🎙️ Podcast'), ('article', '📄 Artigo Externo'), ('merchandise', '🛍️ Merchandise'), ('event', '📅 Evento'), ('musical', '🎵 Musical / Trilha Sonora'), ('audiobook', '🎧 Audiobook'), ('link', '🔗 Link Externo')], max_length=20, verbose_name='Tipo de Conteúdo'),
        ),
        migrations.AlterField(
            model_name='universecontentitem',
            name='platform',
            field=models.CharField(blank=True, help_text='Ex: PC, PS5, Xbox, Netflix, HBO, etc.', max_length=100, verbose_name='Plataforma'),
        ),
        migrations.CreateModel(
            name='UniverseCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Personagem')),
                ('description', models.TextField(blank=True, help_text='Breve descrição do personagem (cuidado com spoilers!)', verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='literary_universes/characters/', verbose_name='Imagem')),
                ('role', models.CharField(choices=[('protagonist', '⭐ Protagonista'), ('antagonist', '💀 Antagonista'), ('supporting', '👤 Coadjuvante'), ('mentor', '🧙 Mentor'), ('other', '📌 Outro')], default='supporting', max_length=20, verbose_name='Papel')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.literaryuniverse', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='literaryuniverse',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Agrupamento temático (ex: Fantasia, Ficção Científica, Mangás)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universes', to='core.universecollection', verbose_name='Coleção'),
        ),
        migrations.CreateModel(
            name='UniverseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Pergunta frequente dos leitores', max_length=300, verbose_name='Pergunta')),
                ('answer', models.TextField(help_text='Resposta completa à pergunta', verbose_name='Resposta')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.literaryuniverse', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes (FAQ)',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UniverseTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='literary_universes/timeline/', verbose_name='Imagem')),
                ('era', models.CharField(blank=True, help_text='Ex: Primeira Era, Anos das Árvores, Terceira Era, etc.', max_length=100, verbose_name='Era / Período')),
                ('approximate_date', models.CharField(blank=True, help_text="Ex: '3019 TE', '~500 anos antes', 'Início da Primeira Era'", max_length=100, verbose_name='Data Aproximada')),
                ('chronological_position', models.IntegerField(default=0, help_text='Número para ordenação cronológica (valores negativos = passado distante)', verbose_name='Posição Cronológica')),
                ('importance', models.CharField(choices=[('critical', '🔴 Crítico (evento que muda tudo)'), ('major', '🟠 Importante'), ('minor', '🟡 Secundário'), ('trivia', '🔵 Curiosidade')], default='major', max_length=10, verbose_name='Importância')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core.literaryuniverse', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Evento da Cronologia',
                'verbose_name_plural': 'Cronologia',
                'ordering': ['chronological_position'],
            },
        ),
        migrations.CreateModel(
            name='UniverseReadingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(help_text='Posição na ordem de leitura recomendada (1, 2, 3...)', verbose_name='Ordem Recomendada')),
                ('title', models.CharField(help_text='Nome do livro/obra', max_length=300, verbose_name='Título')),
                ('book_type', models.CharField(choices=[('novel', '📖 Romance'), ('prelude', '📜 Prelúdio'), ('short_story', '📝 Conto'), ('novella', '📕 Novela'), ('companion', '📚 Companion / Guia'), ('graphic_novel', '🎨 Graphic Novel / HQ'), ('anthology', '📗 Antologia'), ('other', '📄 Outro')], default='novel', max_length=20, verbose_name='Tipo da Obra')),
                ('chronological_order', models.PositiveIntegerField(blank=True, help_text='Posição na ordem cronológica da história (opcional)', null=True, verbose_name='Ordem Cronológica')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('is_essential', models.BooleanField(default=True, help_text='Se marcado, indica que é uma leitura fundamental para a série', verbose_name='Leitura Essencial')),
                ('notes', models.TextField(blank=True, help_text="Notas adicionais (ex: 'Pode ser lido antes ou depois do volume 3')", verbose_name='Observações')),
                ('book', models.ForeignKey(blank=True, help_text='Vincular ao livro no catálogo (opcional — cria link na página)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_order_entries', to='core.book', verbose_name='Livro Vinculado')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_order', to='core.literaryuniverse', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Leitura',
                'verbose_name_plural': 'Ordem de Leitura',
                'ordering': ['order_number'],
                'unique_together': {('universe', 'order_number')},
            },
        ),
    ]
