# Generated by Django 6.0.6 on 2026-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_universecollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universecharacter',
            name='role',
            field=models.CharField(choices=[('protagonist', '⭐ Protagonista'), ('supporting', '🤝 Coadjuvante'), ('mentor', '🎓 Mentor'), ('antagonist', '😈 Antagonista'), ('ruler', '👑 Governante'), ('warrior', '⚔️ Guerreiro'), ('mage', '🧙 Mago'), ('leader', '🧝 Líder'), ('ally', '🛡️ Aliado'), ('other', '❓ Outro')], default='supporting', max_length=20, verbose_name='Papel'),
        ),
    ]
