# Generated by Django 6.0.6 on 2026-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_universecharacter_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universecontentitem',
            name='content_type',
            field=models.CharField(choices=[('review', '✍️ Resenha'), ('game', '🎮 Game'), ('adaptation', '🎬 Adaptação (Filme/Série)'), ('anime', '🎌 Anime'), ('hq', '📚 HQ / Quadrinhos'), ('podcast', '🎙️ Podcast'), ('article', '📄 Artigo Externo'), ('merchandise', '🛍️ Merchandise'), ('event', '📅 Evento'), ('musical', '🎵 Musical / Trilha Sonora'), ('audiobook', '🎧 Audiobook'), ('link', '🔗 Link Externo')], max_length=20, verbose_name='Tipo de Conteúdo'),
        ),
    ]
