# Generated by Django 6.0.6 on 2026-08-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0055_alter_universecontentitem_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRightsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID do Objeto Relacionado')),
                ('image_field_name', models.CharField(help_text='Nome exato do campo de imagem no modelo (ex: hero_banner_image, cover_image).', max_length=100, verbose_name='Campo da Imagem')),
                ('image_file_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Caminho/Nome do Arquivo Auditado')),
                ('image_checksum', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Checksum SHA-256 da Imagem')),
                ('work_title', models.CharField(blank=True, default='', help_text='Título original ou nome dado à ilustração/foto (necessário para atribuição TASL).', max_length=200, verbose_name='Título da Obra Visual')),
                ('credit_name', models.CharField(blank=True, default='', help_text='Nome do artista, fotógrafo, ilustrador ou empresa responsável.', max_length=200, verbose_name='Autor / Criador / Detentor dos Direitos')),
                ('source_url', models.URLField(blank=True, default='', help_text='Link oficial da publicação ou portfólio de onde a imagem foi extraída.', max_length=500, verbose_name='URL da Fonte Original')),
                ('license_type', models.CharField(blank=True, choices=[('own', '🏠 Própria / CG.BookStore'), ('licensed', '📄 Licenciada / Comprada (Banco de Imagens/Estúdio)'), ('cc', '🔀 Creative Commons'), ('public_domain', '🌐 Domínio Público'), ('publisher', '📚 Cortesia da Editora / Divulgação'), ('amazon', '🛒 Amazon Brasil'), ('google_books', '🔍 Google Books'), ('open_library', '📖 Open Library'), ('wikimedia', '🏛️ Wikimedia Commons'), ('other', '📌 Outra')], db_index=True, default='', help_text='Tipo de licença jurídica. Deixe em branco se a licença ainda não foi auditada.', max_length=30, verbose_name='Regime de Licença')),
                ('license_url', models.URLField(blank=True, default='', help_text='Link oficial dos termos da licença (obrigatório/recomendado para Creative Commons).', max_length=500, verbose_name='URL Oficial da Licença')),
                ('is_ai_generated', models.BooleanField(db_index=True, default=False, help_text='Marque se a imagem foi sintetizada por ferramenta de IA (Midjourney, DALL-E, etc.).', verbose_name='Gerada por Inteligência Artificial?')),
                ('usage_notes', models.TextField(blank=True, default='', help_text='Uso interno: detalhes de autorização, cortes, e-mails de autorização.', verbose_name='Observações Internas e Restrições de Uso')),
                ('permission_document', models.FileField(blank=True, help_text='Documento comprobatório privado (Acessível via View autenticada de Admin).', null=True, upload_to='private_copyright_docs/%Y/%m/', verbose_name='Documento Comprobatório / Contrato / Autorização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Cadastro')),
            ],
            options={
                'verbose_name': 'Registro de Direitos Autorais de Imagem',
                'verbose_name_plural': 'Registros de Direitos Autorais de Imagens',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_imager_content_e69b58_idx'), models.Index(fields=['license_type', 'is_ai_generated'], name='core_imager_license_422052_idx')],
                'unique_together': {('content_type', 'object_id', 'image_field_name')},
            },
        ),
    ]
