# Generated by Django 6.0.6 on 2026-08-06 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_imagerightsrecord'),
        ('news', '0007_articlecomment_articlelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Central de Mídia / Vídeo', 'verbose_name_plural': 'Central de Mídias Externas'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='video',
            name='admin_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações Administrativas Internas'),
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.category', verbose_name='Categorias Literárias Relacionadas'),
        ),
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID do Canal na Plataforma'),
        ),
        migrations.AddField(
            model_name='video',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Canal / Criador Original'),
        ),
        migrations.AddField(
            model_name='video',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_td',
            field=models.DurationField(blank=True, help_text='Duração em formato de tempo (DurationField).', null=True, verbose_name='Duração Estruturada'),
        ),
        migrations.AddField(
            model_name='video',
            name='health_check_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem da Última Verificação Técnica'),
        ),
        migrations.AddField(
            model_name='video',
            name='health_check_source',
            field=models.CharField(choices=[('youtube_api', 'YouTube Data API v3'), ('none', 'Nenhum / Não Auditado')], default='none', max_length=30, verbose_name='Fonte de Verificação de Saúde'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_embeddable',
            field=models.BooleanField(blank=True, default=None, help_text='None = Não verificado; True = Permitido; False = Bloqueado.', null=True, verbose_name='Permite Incorporação (Embed)?'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_official_channel',
            field=models.BooleanField(default=False, help_text='Selo de oficialidade (estúdio, editora, autor, desenvolvedora). Requer confirmação auditada.', verbose_name='Canal Oficial Verificado?'),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(default='pt-br', max_length=10, verbose_name='Idioma Principal'),
        ),
        migrations.AddField(
            model_name='video',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação de Saúde'),
        ),
        migrations.AddField(
            model_name='video',
            name='media_status',
            field=models.CharField(choices=[('active', '🟢 Ativa e Disponível'), ('removed', '🔴 Removida da Plataforma'), ('private', '🔒 Privada / Restrita'), ('embed_blocked', '🚫 Incorporação Bloqueada pelo Criador'), ('unavailable', '⚠️ Indisponível'), ('unknown', '❓ Status Não Verificado')], db_index=True, default='unknown', max_length=20, verbose_name='Status de Disponibilidade da Mídia'),
        ),
        migrations.AddField(
            model_name='video',
            name='official_status_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas sobre a Oficialidade do Canal'),
        ),
        migrations.AddField(
            model_name='video',
            name='official_status_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Verificação de Oficialidade'),
        ),
        migrations.AddField(
            model_name='video',
            name='official_status_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Verificação de Oficialidade'),
        ),
        migrations.AddField(
            model_name='video',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_videos', to='news.article', verbose_name='Artigos e Notícias Relacionados'),
        ),
        migrations.AddField(
            model_name='video',
            name='related_quizzes',
            field=models.ManyToManyField(blank=True, related_name='related_videos', to='news.quiz', verbose_name='Quizzes Relacionados'),
        ),
        migrations.AddField(
            model_name='video',
            name='related_universes',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='core.literaryuniverse', verbose_name='Universos Literários Relacionados'),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Resumo sutil para exibições em cards e previews.', max_length=300, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Texto editorial completo contextualizando o vídeo.', verbose_name='Conteúdo Editorial Completo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_code',
            field=models.CharField(blank=True, help_text='Identificador único limpo do vídeo na plataforma (ex: dQw4w9WgXcQ).', max_length=100, verbose_name='ID do Vídeo / Código de Embed'),
        ),
        migrations.AlterField(
            model_name='video',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mídia será exibida em seções especiais da plataforma.', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo (Desabilitado)'), ('instagram', 'Instagram (Desabilitado)'), ('tiktok', 'TikTok (Desabilitado)'), ('upload', 'Upload de Arquivo (Desabilitado)')], default='youtube', max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação Original'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.author', verbose_name='Autor Relacionado Principal'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_books',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.book', verbose_name='Livros Relacionados'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Upload de capa própria. Reutilizará o ImageRightsRecord para governança visual.', null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail Customizada (Capas de Ativos Visuais)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL oficial gerada pelo provedor (ex: img.youtube.com).', max_length=500, verbose_name='URL da Thumbnail Remota'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Título da mídia ou vídeo.', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi'])], verbose_name='Arquivo de Vídeo Local (Desabilitado)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('official_trailer', '🎬 Trailer Oficial'), ('trailer', '📽️ Trailer / Teaser'), ('teaser', '⚡ Teaser'), ('adaptation', '🎥 Adaptação (Filme/Série/Anime)'), ('gameplay', '🎮 Gameplay / Trailer de Jogo'), ('interview', '🎙️ Entrevista / Q&A'), ('behind_the_scenes', '🎞️ Bastidores / Making Of'), ('documentary', '📖 Documentário / Especial'), ('podcast', '🎧 Podcast / Debate'), ('review', '✍️ Resenha em Vídeo / Critique'), ('live', '🔴 Live / Transmissão ao Vivo'), ('event', '🏛️ Evento / Painel'), ('announcement', '📢 Anúncio / Novidade'), ('other', '📌 Outro')], default='other', max_length=30, verbose_name='Tipo de Mídia / Conteúdo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL original informada pelo administrador.', max_length=500, verbose_name='URL do Vídeo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações Internas'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('embed_code__gt', '')), fields=('platform', 'embed_code'), name='unique_video_per_platform'),
        ),
    ]
