# Generated by Django 6.0.6 on 2026-08-24 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0057_alter_video_options_remove_video_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerightsrecord',
            name='display_dimensions',
            field=models.CharField(blank=True, default='', help_text='Dimensões auditadas do arquivo ou formato na interface (ex: 400x600px - Card Preview).', max_length=100, verbose_name='Dimensões de Exibição / Resolução'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='file_size_kb',
            field=models.FloatField(blank=True, null=True, verbose_name='Tamanho do Arquivo (KB)'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='image_height_px',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura (px)'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='image_width_px',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura (px)'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='legal_basis',
            field=models.CharField(blank=True, choices=[('fair_use_art46', '⚖️ Limitação aos Direitos Autorais (Art. 46 Lei 9.610/98 / Fair Use)'), ('express_consent', '📜 Autorização Expressa da Editora/Autor'), ('amazon_affiliate_terms', '🛒 Termos do Programa de Afiliados Amazon'), ('public_domain', '🌐 Domínio Público'), ('creative_commons', '🔀 Licença Creative Commons'), ('own_production', '🏠 Produção Própria / Interna')], db_index=True, default='', help_text='Enquadramento legal para proteção do uso (ex: Art. 46 LDA / Fair Use, Afiliados Amazon).', max_length=30, verbose_name='Fundamento Jurídico'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='usage_purpose',
            field=models.CharField(blank=True, choices=[('review_debate', '💬 Resenha & Debate Literário'), ('affiliate_promotion', '🛒 Divulgação & Afiliado Amazon'), ('author_bio', '👤 Perfil & Biografia de Autor'), ('event_publicity', '📅 Divulgação Gratuita de Evento'), ('adaptation_info', '🎬 Adaptação Literária'), ('institutional', '🎨 Identidade Visual & Layout'), ('other', '📌 Outra')], db_index=True, default='', help_text='Propósito do uso da imagem na aplicação (ex: resenha/debate, indicação de compra).', max_length=30, verbose_name='Finalidade do Uso'),
        ),
        migrations.AddIndex(
            model_name='imagerightsrecord',
            index=models.Index(fields=['usage_purpose', 'legal_basis'], name='core_imager_usage_p_b0cdd0_idx'),
        ),
    ]
