# Generated by Django 6.0.6 on 2026-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_imagerightsrecord_display_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_illustrator',
            field=models.BooleanField(default=False, help_text='Marque se a obra possui ilustrador ou artista responsável pelas artes/ilustrações.', verbose_name='Possui Ilustrador?'),
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator_name',
            field=models.CharField(blank=True, default='', help_text='Nome do artista/ilustrador responsável pelas ilustrações (para crédito legal de direitos autorais).', max_length=200, verbose_name='Nome do Ilustrador'),
        ),
        migrations.AddField(
            model_name='book',
            name='reading_age',
            field=models.CharField(blank=True, default='', help_text='Faixa etária recomendada para leitura (ex: Livre, 10+ anos, 14+ anos, 18+ anos, Infanto-Juvenil).', max_length=50, verbose_name='Idade de Leitura / Faixa Etária'),
        ),
    ]
