# Generated by Django 6.0.6 on 2026-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_book_has_illustrator_book_illustrator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='legal_basis',
            field=models.CharField(blank=True, choices=[('fair_use_art46', '⚖️ Limitação aos Direitos Autorais — Art. 46 da Lei nº 9.610/98'), ('express_consent', '📜 Autorização Expressa da Editora/Autor'), ('amazon_affiliate_terms', '🛒 Termos do Programa de Afiliados Amazon'), ('public_domain', '🌐 Domínio Público'), ('creative_commons', '🔀 Licença Creative Commons'), ('own_production', '🏠 Produção Própria / Interna')], db_index=True, default='', help_text='Enquadramento legal para proteção do uso (ex: Art. 46 da Lei nº 9.610/98, Afiliados Amazon).', max_length=30, verbose_name='Fundamento Jurídico'),
        ),
    ]
