# Generated by Django 6.0.6 on 2026-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_imagerightsrecord_legal_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='legal_basis',
            field=models.CharField(blank=True, choices=[('fair_use_art46', '⚖️ Limitação legal analisada — Lei nº 9.610/98, Art. 46'), ('express_consent', '📜 Autorização Expressa da Editora/Autor'), ('amazon_affiliate_terms', '🛒 Termos do Programa de Afiliados Amazon'), ('public_domain', '🌐 Domínio Público'), ('creative_commons', '🔀 Licença Creative Commons'), ('own_production', '🏠 Produção Própria / Interna')], db_index=True, default='', help_text='Enquadramento legal para registro de conformidade (ex: Lei nº 9.610/98, Art. 46, Termos de Afiliados).', max_length=30, verbose_name='Fundamento Jurídico'),
        ),
    ]
