# Generated by Django 6.0.6 on 2026-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_imagerightsrecord_legal_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerightsrecord',
            name='creator_name',
            field=models.CharField(blank=True, default='', help_text='Nome da pessoa física ou artista que efetivamente produziu a obra visual (ex: fotógrafo, ilustrador, designer).', max_length=255, verbose_name='Criador / Autor da Imagem'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='licensor_name',
            field=models.CharField(blank=True, default='', help_text='Entidade, banco de imagens, agência ou distribuidora que concede ou administra a licença de uso da imagem.', max_length=255, verbose_name='Licenciante / Entidade Administradora'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='rights_holder_name',
            field=models.CharField(blank=True, default='', help_text='Pessoa física ou jurídica detentora dos direitos patrimoniais da imagem, quando confirmada.', max_length=255, verbose_name='Titular dos Direitos'),
        ),
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='credit_name',
            field=models.CharField(blank=True, default='', help_text='Campo de compatibilidade histórica para créditos gerais não estruturados.', max_length=255, verbose_name='Crédito Legado / Atribuição Geral'),
        ),
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Indica onde a imagem foi encontrada ou obtida. A existência de uma fonte não representa, por si só, autorização de uso.', max_length=500, verbose_name='Fonte Original da Imagem'),
        ),
    ]
