# Generated by Django 6.0.6 on 2026-08-31 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0062_imagerightsrecord_creator_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerightsrecord',
            name='audit_status',
            field=models.CharField(choices=[('not_audited', '⚪ Não auditada'), ('under_review', '🔵 Em análise'), ('regularized', '🟢 Regularizada'), ('pending', '🟡 Pendente de documentação'), ('contested', '🔴 Contestada'), ('restricted', '⛔ Uso Restrito / Suspenso')], db_index=True, default='not_audited', help_text="Conclusão administrativa da auditoria documental do ativo visual. Registros novos ou não revisados iniciam como '⚪ Não auditada'.", max_length=30, verbose_name='Status de Auditoria e Governança'),
        ),
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='license_type',
            field=models.CharField(blank=True, choices=[('own', '🏠 Própria / CG.BookStore (Criação Interna)'), ('licensed', '📄 Licenciada / Comprada (Banco de Imagens / Contrato)'), ('cc', '🔀 Creative Commons (Licença Aberta)'), ('public_domain', '🌐 Domínio Público (Obra Livre)'), ('publisher', '📚 Origem: Editora / Divulgação (Procedência Histórica)'), ('amazon', '🛒 Origem: Amazon Brasil (Procedência Técnica)'), ('google_books', '🔍 Origem: Google Books (Procedência Técnica)'), ('open_library', '📖 Origem: Open Library (Procedência Técnica)'), ('wikimedia', '🏛️ Origem: Wikimedia Commons (Procedência Técnica)'), ('other', '📌 Outra Licença / Procedência')], db_index=True, default='', help_text='Regime jurídico de utilização da imagem. Atenção: opções de catálogo/plataforma (Amazon, Google Books, etc.) indicam apenas procedência técnica histórica e não autorizam o uso de forma automática.', max_length=30, verbose_name='Regime de Licença / Procedência Histórica'),
        ),
        migrations.AddIndex(
            model_name='imagerightsrecord',
            index=models.Index(fields=['audit_status'], name='core_imager_audit_s_69f815_idx'),
        ),
    ]
