# Generated by Django 6.0.6 on 2026-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_imagerightsrecord_audit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='audit_status',
            field=models.CharField(blank=True, choices=[('not_audited', '⚪ Não auditada'), ('under_review', '🔵 Em análise'), ('regularized', '🟢 Regularizada'), ('pending', '🟡 Pendente de documentação'), ('contested', '🔴 Contestada'), ('restricted', '⛔ Uso Restrito / Suspenso')], db_index=True, default='not_audited', help_text="Conclusão administrativa da auditoria documental do ativo visual. Registros novos ou não revisados iniciam como '⚪ Não auditada'.", max_length=30, verbose_name='Status de Auditoria e Governança'),
        ),
    ]
