# Generated by Django 6.0.6 on 2026-08-31 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0065_recreate_weekly_chronicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightTakedownRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', '📥 Recebida'), ('under_review', '🔍 Em análise'), ('awaiting_information', '🟡 Aguardando informações'), ('temporarily_suspended', '⛔ Imagem suspensa preventivamente'), ('resolved_keep', '🟢 Resolvida — uso mantido'), ('resolved_removed', '🔴 Resolvida — imagem retirada'), ('rejected', '⚪ Reclamação rejeitada / não procedente')], db_index=True, default='received', help_text='Estado atual do tratamento administrativo da ocorrência.', max_length=30, verbose_name='Status da Contestação')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Momento em que a notificação ou reclamação foi recebida pela plataforma.', verbose_name='Data/Hora de Recebimento')),
                ('claimant_name', models.CharField(blank=True, default='', help_text='Nome da pessoa física ou contato responsável pela contestação.', max_length=255, verbose_name='Nome do Reclamante')),
                ('claimant_email', models.EmailField(blank=True, default='', help_text='E-mail utilizado para comunicações formais sobre o caso.', max_length=254, verbose_name='E-mail de Contato')),
                ('claimant_organization', models.CharField(blank=True, default='', help_text='Empresa, escritório jurídico, agência ou editora representada, se houver.', max_length=255, verbose_name='Organização / Editora / Escritório')),
                ('claimant_role', models.CharField(blank=True, choices=[('rights_holder', 'Titular dos Direitos Patrimoniais'), ('authorized_representative', 'Representante / Procurador Autorizado'), ('creator_author', 'Autor / Criador da Obra Visual'), ('publisher_licensor', 'Editora / Agência Licenciante'), ('third_party', 'Terceiro Interessado'), ('unknown', 'Não Informado / Desconhecido'), ('other', 'Outro')], default='rights_holder', max_length=40, verbose_name='Papel Declarado do Reclamante')),
                ('claim_description', models.TextField(help_text='Resumo detalhado dos fatos e motivos alegados pelo reclamante.', verbose_name='Descrição da Reclamação')),
                ('claimed_rights_basis', models.TextField(blank=True, default='', help_text='Base legal ou contratual apontada pelo reclamante (ex: titularidade de copyright, ausência de licença).', verbose_name='Fundamento Jurídico Alegado')),
                ('source_notice_url', models.URLField(blank=True, default='', help_text='Link oficial da obra original, portfólio do autor ou notificação externa.', max_length=500, verbose_name='URL da Notificação / Referência Original')),
                ('evidence_document', models.FileField(blank=True, help_text='Arquivo restrito a administradores (notificação extrajudicial, procuração, certidão de registro).', null=True, upload_to='private_takedown_docs/%Y/%m/', verbose_name='Documento / Notificação Comprobatória (Privado)')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Anotações internas sobre a análise, parecer jurídico e comunicações com o reclamante.', verbose_name='Notas Administrativas Privadas')),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Fundamentação da decisão final adotada pela administração.', verbose_name='Justificativa da Resolução')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Momento em que o caso foi formalmente encerrado.', null=True, verbose_name='Data/Hora de Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ocorrência de Contestação / Takedown',
                'verbose_name_plural': 'Ocorrências de Contestação / Takedown',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='public_display_allowed',
            field=models.BooleanField(db_index=True, default=True, help_text='Determina administrativamente se a imagem pode ser exibida publicamente na plataforma. É independente de audit_status: caso desmarcado ou em suspensão preventiva por contestação, a exibição pública é bloqueada sem apagar o arquivo original nem o histórico.', verbose_name='Exibição Pública Permitida?'),
        ),
        migrations.AddIndex(
            model_name='imagerightsrecord',
            index=models.Index(fields=['public_display_allowed'], name='core_imager_public__3bdc46_idx'),
        ),
        migrations.AddField(
            model_name='copyrighttakedownrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_takedowns', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='copyrighttakedownrequest',
            name='image_rights_record',
            field=models.ForeignKey(help_text='Ativo visual objeto da notificação ou contestação.', on_delete=django.db.models.deletion.CASCADE, related_name='takedown_requests', to='core.imagerightsrecord', verbose_name='Registro de Direitos Autorais Contestado'),
        ),
        migrations.AddField(
            model_name='copyrighttakedownrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_takedowns', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por'),
        ),
        migrations.AddIndex(
            model_name='copyrighttakedownrequest',
            index=models.Index(fields=['status', 'received_at'], name='core_copyri_status_c938eb_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrighttakedownrequest',
            index=models.Index(fields=['image_rights_record', 'status'], name='core_copyri_image_r_7018c6_idx'),
        ),
    ]
