# Generated by Django 6.0.6 on 2026-08-31 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_add_copyright_takedown_and_public_display'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRightsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('record_created', '✨ Registro Criado'), ('record_updated', '✏️ Registro Atualizado'), ('creator_changed', '👤 Autor/Criador Alterado'), ('rights_holder_changed', '🏛️ Titular dos Direitos Alterado'), ('licensor_changed', '🏢 Licenciante Alterado'), ('source_changed', '🌐 Fonte Original Alterada'), ('license_changed', '📄 Regime de Licença Alterado'), ('legal_basis_changed', '⚖️ Fundamento Jurídico Alterado'), ('audit_status_changed', '📊 Status de Auditoria Alterado'), ('public_display_changed', '👁️ Exibição Pública Alterada'), ('permission_document_changed', '📜 Documento Comprobatório Alterado'), ('takedown_received', '📥 Contestação Recebida'), ('takedown_status_changed', '🔄 Status da Contestação Alterado'), ('image_suspended', '⛔ Imagem Suspensa Preventivamente'), ('image_restored', '🟢 Exibição da Imagem Restaurada'), ('takedown_resolved_keep', '✅ Contestação Resolvida — Uso Mantido'), ('takedown_resolved_removed', '🛑 Contestação Resolvida — Imagem Retirada'), ('integrity_divergence_detected', '⚠️ Divergência de Integridade Detectada'), ('checksum_updated', '🔄 Checksum Recalculado/Atualizado')], db_index=True, help_text='Classificação estruturada do evento histórico.', max_length=40, verbose_name='Tipo de Evento')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Momento exato em que o evento ocorreu (imutável).', verbose_name='Data/Hora do Evento')),
                ('source', models.CharField(choices=[('admin', 'Django Admin'), ('service', 'Serviço Interno'), ('command', 'Comando de Gerenciamento'), ('migration', 'Migração / Importação'), ('system', 'Sistema / Automático')], db_index=True, default='service', help_text='Canal ou processo de onde partiu a modificação.', max_length=30, verbose_name='Origem da Alteração')),
                ('field_name', models.CharField(blank=True, default='', help_text='Nome técnico do campo modificado, quando aplicável.', max_length=100, verbose_name='Campo Alterado')),
                ('old_value', models.CharField(blank=True, default='', help_text='Representação sanitizada do valor anterior (sem dados sensíveis ou caminhos privados).', max_length=500, verbose_name='Valor Anterior (Seguro)')),
                ('new_value', models.CharField(blank=True, default='', help_text='Representação sanitizada do novo valor.', max_length=500, verbose_name='Novo Valor (Seguro)')),
                ('description', models.CharField(help_text='Resumo humano objetivo da ação executada.', max_length=500, verbose_name='Descrição do Evento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações técnicas contextuais adicionais que não contenham dados pessoais ou arquivos confidenciais.', verbose_name='Metadados Técnicos')),
                ('image_rights_record', models.ForeignKey(help_text='Ativo visual associado a este evento de governança.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.imagerightsrecord', verbose_name='Registro de Direitos Autorais')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Administrador ou usuário que realizou ou autorizou a alteração.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_rights_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('takedown_request', models.ForeignKey(blank=True, help_text='Notificação ou contestação associada a este evento, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.copyrighttakedownrequest', verbose_name='Contestação Relacionada')),
            ],
            options={
                'verbose_name': '📜 Log de Auditoria de Direitos Autorais',
                'verbose_name_plural': '📜 Trilha Histórica de Auditoria de Imagens',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['image_rights_record', '-created_at'], name='core_imager_image_r_fab897_idx'), models.Index(fields=['event_type', '-created_at'], name='core_imager_event_t_c73381_idx'), models.Index(fields=['source', '-created_at'], name='core_imager_source_8ee6fc_idx')],
            },
        ),
    ]
