# Generated by Django 6.0.6 on 2026-08-31 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_imagerightsauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrighttakedownrequest',
            name='image_rights_record',
            field=models.ForeignKey(help_text='Ativo visual objeto da notificação ou contestação.', on_delete=django.db.models.deletion.PROTECT, related_name='takedown_requests', to='core.imagerightsrecord', verbose_name='Registro de Direitos Autorais Contestado'),
        ),
        migrations.AlterField(
            model_name='imagerightsauditlog',
            name='image_rights_record',
            field=models.ForeignKey(help_text='Ativo visual associado a este evento de governança.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.imagerightsrecord', verbose_name='Registro de Direitos Autorais'),
        ),
    ]
