# Generated by Django 6.0.6 on 2026-08-31 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0068_alter_copyrighttakedownrequest_image_rights_record_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerightsrecord',
            name='is_auto_imported',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se os dados visuais e de proveniência nasceram através de rotinas e integrações automáticas.', verbose_name='Importado Automaticamente?'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='provenance_imported_at',
            field=models.DateTimeField(blank=True, help_text='Momento em que o ativo visual foi importado do provedor externo.', null=True, verbose_name='Data/Hora da Importação Técnica'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='provenance_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot estruturado de metadados técnicos seguros fornecidos pela API/fonte (sem tokens, dados pessoais ou headers).', verbose_name='Metadados Seguros de Proveniência'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='provenance_method',
            field=models.CharField(blank=True, default='', help_text='Canal técnico de aquisição (ex: api_download, api_reference, rss_sync, manual_import).', max_length=50, verbose_name='Método de Importação'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='provenance_provider',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identifica a fonte/serviço externo de onde o arquivo ou referência foi obtido (ex: google_books, open_library, unsplash, wikimedia).', max_length=50, verbose_name='Provedor Técnico de Proveniência'),
        ),
        migrations.AddField(
            model_name='imagerightsrecord',
            name='provider_asset_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID do ativo no catálogo da fonte externa (ex: Google Book ID, OpenLibrary Work ID, Unsplash Photo ID).', max_length=255, verbose_name='Identificador Externo do Ativo'),
        ),
        migrations.AlterField(
            model_name='imagerightsauditlog',
            name='event_type',
            field=models.CharField(choices=[('record_created', '✨ Registro Criado'), ('record_updated', '✏️ Registro Atualizado'), ('creator_changed', '👤 Autor/Criador Alterado'), ('rights_holder_changed', '🏛️ Titular dos Direitos Alterado'), ('licensor_changed', '🏢 Licenciante Alterado'), ('source_changed', '🌐 Fonte Original Alterada'), ('license_changed', '📄 Regime de Licença Alterado'), ('legal_basis_changed', '⚖️ Fundamento Jurídico Alterado'), ('audit_status_changed', '📊 Status de Auditoria Alterado'), ('public_display_changed', '👁️ Exibição Pública Alterada'), ('permission_document_changed', '📜 Documento Comprobatório Alterado'), ('takedown_received', '📥 Contestação Recebida'), ('takedown_status_changed', '🔄 Status da Contestação Alterado'), ('image_suspended', '⛔ Imagem Suspensa Preventivamente'), ('image_restored', '🟢 Exibição da Imagem Restaurada'), ('takedown_resolved_keep', '✅ Contestação Resolvida — Uso Mantido'), ('takedown_resolved_removed', '🛑 Contestação Resolvida — Imagem Retirada'), ('integrity_divergence_detected', '⚠️ Divergência de Integridade Detectada'), ('checksum_updated', '🔄 Checksum Recalculado/Atualizado'), ('provenance_registered', '🔗 Proveniência Técnica Registrada'), ('provenance_updated', '🔄 Proveniência Técnica Atualizada'), ('provenance_conflict_detected', '⚠️ Conflito de Proveniência Detectado')], db_index=True, help_text='Classificação estruturada do evento histórico.', max_length=40, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='imagerightsauditlog',
            name='source',
            field=models.CharField(choices=[('admin', 'Django Admin'), ('service', 'Serviço Interno'), ('command', 'Comando de Gerenciamento'), ('integration', 'Integração Externa / API'), ('migration', 'Migração / Importação'), ('system', 'Sistema / Automático')], db_index=True, default='service', help_text='Canal ou processo de onde partiu a modificação.', max_length=30, verbose_name='Origem da Alteração'),
        ),
        migrations.AddIndex(
            model_name='imagerightsrecord',
            index=models.Index(fields=['provenance_provider', 'is_auto_imported'], name='core_imager_provena_cf4b06_idx'),
        ),
    ]
