# Generated by Django 6.0.6 on 2026-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_imagerightsrecord_is_auto_imported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='license_type',
            field=models.CharField(blank=True, choices=[('own', '🏠 Própria / CG.BookStore (Criação Interna)'), ('licensed', '📄 Licenciada / Comprada (Banco de Imagens / Contrato)'), ('cc', '🔀 Creative Commons (Licença Aberta)'), ('public_domain', '🌐 Domínio Público (Obra Livre)'), ('publisher', '📚 Origem: Editora / Divulgação (Procedência Histórica)'), ('amazon', '🛒 Origem: Amazon Brasil (Procedência Técnica)'), ('google_books', '🔍 Origem: Google Books (Procedência Técnica)'), ('open_library', '📖 Origem: Open Library (Procedência Técnica)'), ('project_gutenberg', '📜 Origem: Project Gutenberg (Procedência Técnica)'), ('wikimedia', '🏛️ Origem: Wikimedia Commons (Procedência Técnica)'), ('other', '📌 Outra Licença / Procedência')], db_index=True, default='', help_text='Regime jurídico de utilização da imagem. Atenção: opções de catálogo/plataforma (Amazon, Google Books, etc.) indicam apenas procedência técnica histórica e não autorizam o uso de forma automática.', max_length=30, verbose_name='Regime de Licença / Procedência Histórica'),
        ),
        migrations.AlterField(
            model_name='imagerightsrecord',
            name='provenance_provider',
            field=models.CharField(blank=True, choices=[('google_books', '🔍 Google Books API'), ('open_library', '📖 Open Library'), ('project_gutenberg', '📜 Project Gutenberg'), ('unsplash', '📷 Unsplash API'), ('wikimedia', '🏛️ Wikimedia Commons'), ('publisher', '📚 Editora / Material de Divulgação'), ('amazon', '🛒 Amazon (Afiliados / Referência Técnica)'), ('external_api', '🌐 Outra API Externa'), ('internal_ai', '🤖 IA Interna (Geração Própria)'), ('partner', '🤝 Parceiro Institucional'), ('other', '📌 Outro Provedor Técnico')], db_index=True, default='', help_text='Identifica a fonte/serviço externo de onde o arquivo ou referência foi obtido (ex: google_books, open_library, project_gutenberg, unsplash, wikimedia).', max_length=50, verbose_name='Provedor Técnico de Proveniência'),
        ),
    ]
