# Generated by Django 6.0.6 on 2026-09-05 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_imagerightsrecord_license_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRightsResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '⏳ Não iniciada'), ('running', '🔄 Em andamento'), ('completed', '✅ Concluída'), ('partial', '⚠️ Parcial (fontes indisponíveis)'), ('failed', '❌ Falha técnica')], db_index=True, default='not_started', max_length=20, verbose_name='Status da Pesquisa')),
                ('researched_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Pesquisa')),
                ('internal_data_used', models.JSONField(blank=True, default=dict, help_text='Snapshot dos dados internos disponíveis no momento da pesquisa (ISBN, título, autor, editora, provider_asset_id, etc.).', verbose_name='Dados Internos Utilizados')),
                ('sources_consulted', models.JSONField(blank=True, default=list, help_text='Lista de fontes consultadas com status individual. Cada entrada: {source_name, source_type, url, status, retrieved_at, error}.', verbose_name='Fontes Consultadas')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='Lista de propostas estruturadas. Cada entrada: {field_name, suggested_value, current_value, source_url, source_type, source_title, retrieved_at, confidence, short_reason, is_divergent}.', verbose_name='Sugestões de Preenchimento')),
                ('conflicts', models.JSONField(blank=True, default=list, help_text='Divergências entre fontes confiáveis. Cada entrada: {field_name, source_a, value_a, source_b, value_b, note}.', verbose_name='Conflitos Identificados')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Lista de erros de APIs ou fontes indisponíveis durante a pesquisa.', verbose_name='Erros Técnicos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('image_rights_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_results', to='core.imagerightsrecord', verbose_name='Registro de Direitos Associado')),
                ('researched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pesquisa realizada por')),
            ],
            options={
                'verbose_name': 'Resultado de Pesquisa Assistida',
                'verbose_name_plural': 'Resultados de Pesquisa Assistida',
                'ordering': ['-researched_at'],
                'indexes': [models.Index(fields=['image_rights_record', '-researched_at'], name='core_imager_image_r_22f740_idx'), models.Index(fields=['status'], name='core_imager_status_4b3787_idx')],
            },
        ),
    ]
