# Generated by Django 6.0.6 on 2026-09-05 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_imagerightsresearchresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Nome canônico da editora (ex: 'HarperCollins Brasil', 'Companhia das Letras').", max_length=255, unique=True, verbose_name='Nome da Instituição / Editora')),
                ('domain', models.CharField(db_index=True, help_text="Domínio limpo sem protocolo ou caminhos (ex: 'harpercollins.com.br').", max_length=255, unique=True, verbose_name='Domínio Oficial')),
                ('institution_type', models.CharField(choices=[('publisher', '📚 Editora / Selo Editorial'), ('author_estate', '🖋️ Espólio / Fundação de Autor'), ('cultural_institution', '🏛️ Museu / Arquivo / Instituição Cultural'), ('academic', '🎓 Editora Universitária / Acadêmica'), ('agency', '🏢 Agência Literária / Representação'), ('other', '🌐 Outro')], default='publisher', max_length=30, verbose_name='Tipo da Instituição')),
                ('main_url', models.URLField(blank=True, help_text="URL completa do site institucional oficial (ex: 'https://harpercollins.com.br').", max_length=500, verbose_name='URL Principal / Site Oficial')),
                ('terms_url', models.URLField(blank=True, help_text='Página institucional oficial de Termos de Uso / Condições Gerais.', max_length=500, verbose_name='URL de Termos de Uso')),
                ('permissions_url', models.URLField(blank=True, help_text='Página institucional de Direitos, Permissions, Media ou Contato de Licenciamento.', max_length=500, verbose_name='URL de Permissões / Direitos / Imprensa')),
                ('terms_summary', models.TextField(blank=True, help_text='Resumo factual e operacional curto das diretrizes de conteúdo identificadas (sem parecer jurídico).', verbose_name='Resumo Operacional dos Termos')),
                ('terms_content_hash', models.CharField(blank=True, help_text='Hash SHA-256 do trecho analisado para detecção de alterações na página institucional.', max_length=64, verbose_name='Hash do Conteúdo dos Termos')),
                ('terms_retrieved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Consulta dos Termos')),
                ('is_verified', models.BooleanField(default=True, help_text='Indica se o domínio institucional foi validado (por curadoria ou confirmação administrativa).', verbose_name='Domínio Verificado')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Validação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_institutional_sources', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Fonte Institucional Oficial',
                'verbose_name_plural': 'Fontes Institucionais Oficiais',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['domain'], name='core_instit_domain_98cc19_idx'), models.Index(fields=['name'], name='core_instit_name_76268a_idx'), models.Index(fields=['is_active', 'is_verified'], name='core_instit_is_acti_b31c69_idx')],
            },
        ),
    ]
