# Generated by Django 5.0.3 on 2025-11-03 11:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('product_type', models.CharField(choices=[('physical', 'Livro Físico'), ('digital', 'Livro Digital (eBook)'), ('both', 'Físico + Digital')], default='physical', max_length=20, verbose_name='Tipo de Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Editora')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='Imagem da Capa')),
                ('digital_file', models.URLField(blank=True, null=True, verbose_name='Arquivo Digital (URL Supabase)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], max_length=20, verbose_name='Método de Pagamento')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('shipping_address', models.TextField(verbose_name='Endereço de Entrega')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('shipping_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('shipping_zipcode', models.CharField(max_length=9, verbose_name='CEP')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo de Envio')),
                ('mp_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Pagamento MP')),
                ('mp_preference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Preferência MP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendente', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], max_length=20, verbose_name='Método de Pagamento')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('9.90'), max_digits=10, verbose_name='Valor Mensal')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Cobrança')),
                ('mp_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Assinatura MP')),
                ('mp_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Pagamento MP')),
                ('mp_preference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Preferência MP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription', 'Assinatura'), ('order', 'Pedido'), ('refund', 'Reembolso'), ('webhook', 'Webhook')], max_length=20, verbose_name='Tipo de Transação')),
                ('mp_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Pagamento MP')),
                ('mp_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status MP')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.order', verbose_name='Pedido')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.subscription', verbose_name='Assinatura')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Transação',
                'verbose_name_plural': 'Logs de Transações',
                'ordering': ['-created_at'],
            },
        ),
    ]
