# Generated by Django 5.0.3 on 2025-11-03 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo para a campanha', max_length=200, verbose_name='Nome da Campanha')),
                ('description', models.TextField(help_text='Detalhes sobre o objetivo e público-alvo da campanha', verbose_name='Descrição')),
                ('duration_days', models.IntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias')], default=7, help_text='Quantos dias de Premium gratuito serão concedidos', verbose_name='Duração do Premium Gratuito')),
                ('target_type', models.CharField(choices=[('individual', 'Usuário Individual'), ('group', 'Grupo de Usuários'), ('new_users', 'Novos Usuários'), ('birthdays', 'Aniversariantes do Mês'), ('custom', 'Critério Personalizado')], default='custom', help_text='Como os usuários serão selecionados', max_length=20, verbose_name='Tipo de Público-Alvo')),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Filtros e condições para selecionar usuários (formato JSON)', verbose_name='Critérios de Seleção')),
                ('start_date', models.DateTimeField(help_text='Quando a campanha começa a vigorar', verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(help_text='Quando a campanha termina', verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status da Campanha')),
                ('auto_grant', models.BooleanField(default=True, help_text='Se marcado, o Premium será concedido automaticamente aos usuários elegíveis', verbose_name='Concessão Automática')),
                ('max_grants', models.IntegerField(blank=True, help_text='Número máximo de usuários que podem receber (deixe em branco para ilimitado)', null=True, verbose_name='Limite de Concessões')),
                ('total_granted', models.IntegerField(default=0, help_text='Quantos usuários já receberam Premium nesta campanha', verbose_name='Total Concedido')),
                ('total_eligible', models.IntegerField(default=0, help_text='Quantos usuários são elegíveis segundo os critérios', verbose_name='Total Elegível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Campanha de Marketing',
                'verbose_name_plural': 'Campanhas de Marketing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revogado em')),
                ('is_active', models.BooleanField(default=True, help_text='Se o Premium concedido ainda está ativo', verbose_name='Ativo')),
                ('was_notified', models.BooleanField(default=False, help_text='Se o usuário foi notificado por email sobre a concessão', verbose_name='Usuário Notificado')),
                ('reason', models.TextField(blank=True, help_text='Motivo específico da concessão ou observações do administrador', verbose_name='Motivo/Observações')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='finance.campaign', verbose_name='Campanha')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_grants', to='finance.subscription', verbose_name='Assinatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_grants', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Concessão de Campanha',
                'verbose_name_plural': 'Concessões de Campanhas',
                'ordering': ['-granted_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
