# Generated by Django 5.0.3 on 2025-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_campaign_campaigngrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='execution_count',
            field=models.IntegerField(default=0, help_text='Quantas vezes esta campanha foi executada manualmente', verbose_name='Número de Execuções'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_execution_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última vez que a campanha foi executada', null=True, verbose_name='Última Execução'),
        ),
    ]
