# Generated by Django 5.0.3 on 2025-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_campaign_execution_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_notification',
            field=models.BooleanField(default=True, help_text='Se marcado, os usuários receberão uma notificação no sininho quando receberem Premium', verbose_name='Enviar Notificação'),
        ),
    ]
