# Generated by Django 5.0.3 on 2025-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        # Adicionar índice composto para queries comuns em posts
        migrations.AddIndex(
            model_name='debatepost',
            index=models.Index(
                fields=['topic', '-created_at', 'is_deleted'],
                name='idx_post_topic_date'
            ),
        ),
        # Adicionar índice para ordenação de tópicos por pinned e data
        migrations.AddIndex(
            model_name='debatetopic',
            index=models.Index(
                fields=['-is_pinned', '-updated_at'],
                name='idx_topic_pinned_date'
            ),
        ),
        # Adicionar índice para busca de posts não deletados
        migrations.AddIndex(
            model_name='debatepost',
            index=models.Index(
                fields=['is_deleted', 'parent'],
                name='idx_post_deleted_parent'
            ),
        ),
    ]
