# Generated by Django 5.1.1 on 2025-11-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debatepost',
            name='idx_post_topic_date',
        ),
        migrations.RemoveIndex(
            model_name='debatepost',
            name='idx_post_deleted_parent',
        ),
        migrations.RemoveIndex(
            model_name='debatetopic',
            name='idx_topic_pinned_date',
        ),
    ]
