# Generated by Django 5.1.1 on 2026-07-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('tracking_id', models.CharField(blank=True, help_text='Identificador de afiliado para rastreamento de comissões (ex: cgbookstore-20)', max_length=100, verbose_name='ID de Rastreamento (Tracking ID)')),
                ('url_base', models.URLField(blank=True, help_text='URL base do parceiro se aplicável para redirecionamento', max_length=500, verbose_name='URL Base')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Logo do Parceiro')),
                ('cor_botao', models.CharField(blank=True, help_text='Classe CSS do Bootstrap (ex: btn-warning, btn-success) ou cor hexadecimal (ex: #FF9900)', max_length=50, verbose_name='Cor do Botão')),
                ('icone', models.CharField(blank=True, help_text='Classe CSS do FontAwesome para o ícone do botão (ex: fab fa-amazon, fas fa-shopping-cart)', max_length=50, verbose_name='Ícone')),
                ('ativo', models.BooleanField(default=True, help_text='Se desmarcado, este parceiro e seus links de afiliado não serão ativados', verbose_name='Ativo')),
                ('prioridade', models.IntegerField(default=0, help_text='Ordenação de prioridade (valores maiores têm maior preferência)', verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Parceiro Comercial',
                'verbose_name_plural': 'Parceiros Comerciais',
                'ordering': ['-prioridade', 'nome'],
            },
        ),
    ]
