# Generated by Django 5.1.1 on 2026-07-09 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_section_layout'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePartnerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Identifica acessos de usuários anônimos', max_length=40, verbose_name='Chave de Sessão')),
                ('destination_url', models.URLField(max_length=1000, verbose_name='URL de Destino')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('device', models.CharField(blank=True, max_length=50, verbose_name='Dispositivo')),
                ('referer', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Referer')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Idioma do Navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='core.book', verbose_name='Livro')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='partners.affiliatepartner', verbose_name='Parceiro Comercial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Clique em Parceiro',
                'verbose_name_plural': 'Cliques em Parceiros',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='partners_af_created_427af3_idx'), models.Index(fields=['device'], name='partners_af_device_2eeb8f_idx'), models.Index(fields=['browser'], name='partners_af_browser_baa640_idx'), models.Index(fields=['os'], name='partners_af_os_c153ea_idx')],
            },
        ),
    ]
