# Generated by Django 6.0.6 on 2026-07-17 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='session_key do Django — identifica anônimos e autenticados', max_length=40, verbose_name='Chave de Sessão')),
                ('is_authenticated', models.BooleanField(db_index=True, default=False, verbose_name='Autenticado')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Início da Sessão')),
                ('last_activity_at', models.DateTimeField(verbose_name='Última Atividade')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Preenchido quando session_ended é registrado ou por timeout', null=True, verbose_name='Encerramento da Sessão')),
                ('entry_page', models.CharField(blank=True, default='', help_text='Primeira página acessada nesta sessão (normalizada)', max_length=100, verbose_name='Página de Entrada')),
                ('exit_page', models.CharField(blank=True, default='', help_text='Última página acessada nesta sessão (normalizada)', max_length=100, verbose_name='Página de Saída')),
                ('referer_domain', models.CharField(blank=True, default='', help_text='Domínio do cabeçalho Referer sem path (ex: google.com)', max_length=200, verbose_name='Domínio de Origem')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='Fonte (UTM Source)')),
                ('medium', models.CharField(blank=True, default='', max_length=100, verbose_name='Meio (UTM Medium)')),
                ('campaign', models.CharField(blank=True, default='', max_length=200, verbose_name='Campanha (UTM Campaign)')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Desconhecido')], db_index=True, default='unknown', max_length=20, verbose_name='Tipo de Dispositivo')),
                ('browser_family', models.CharField(blank=True, default='', help_text='Ex: Chrome, Firefox, Safari — sem versão', max_length=100, verbose_name='Família do Navegador')),
                ('operating_system', models.CharField(blank=True, default='', help_text='Ex: Windows, Android, iOS — sem versão', max_length=100, verbose_name='Sistema Operacional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(blank=True, help_text='Nulo para visitantes não autenticados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão Analítica',
                'verbose_name_plural': 'Sessões Analíticas',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('metric_name', models.CharField(db_index=True, help_text='Ex: dau, wau, mau, retention_d1, premium_conversions', max_length=100, verbose_name='Nome da Métrica')),
                ('dimension', models.CharField(blank=True, default='', help_text='Ex: device_type, source, is_authenticated', max_length=100, verbose_name='Dimensão')),
                ('dimension_value', models.CharField(blank=True, default='', help_text='Ex: mobile, google.com, true', max_length=200, verbose_name='Valor da Dimensão')),
                ('value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor')),
                ('source_apps', models.JSONField(blank=True, default=list, help_text='Lista dos apps Django que contribuíram para o cálculo', verbose_name='Apps de Origem')),
                ('is_partial', models.BooleanField(default=False, help_text='True quando a métrica não pode ser completamente reconstruída para esta data (ex: rastreamento ainda não estava ativo)', verbose_name='Dados Parciais')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Computado em')),
            ],
            options={
                'verbose_name': 'Snapshot de Métrica Diária',
                'verbose_name_plural': 'Snapshots de Métricas Diárias',
                'ordering': ['-date', 'metric_name'],
                'indexes': [models.Index(fields=['-date', 'metric_name'], name='pa_snapshot_date_metric_idx'), models.Index(fields=['metric_name', '-date'], name='pa_snapshot_metric_date_idx')],
                'unique_together': {('date', 'metric_name', 'dimension', 'dimension_value')},
            },
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='Somente valores da allowlist ALLOWED_EVENT_TYPES', max_length=50, verbose_name='Tipo de Evento')),
                ('page_name', models.CharField(blank=True, db_index=True, default='', help_text='Nome normalizado da página (não a URL bruta)', max_length=100, verbose_name='Nome da Página')),
                ('object_type', models.CharField(blank=True, default='', help_text='Ex: book, author, article (opcional)', max_length=50, verbose_name='Tipo do Objeto')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='PK do objeto referenciado (opcional)', null=True, verbose_name='ID do Objeto')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Chaves restritas pela allowlist ALLOWED_METADATA_KEYS', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='product_analytics.analyticssession', verbose_name='Sessão')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Evento de Produto',
                'verbose_name_plural': 'Eventos de Produto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['-started_at'], name='pa_session_started_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['user', '-started_at'], name='pa_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['session_key', '-started_at'], name='pa_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['device_type', '-started_at'], name='pa_session_device_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['is_authenticated', '-started_at'], name='pa_session_auth_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['event_type', '-created_at'], name='pa_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['user', '-created_at'], name='pa_event_user_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['session', '-created_at'], name='pa_event_session_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['page_name', '-created_at'], name='pa_event_page_idx'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['created_at'], name='pa_event_created_purge_idx'),
        ),
    ]
