# Generated by Django 6.0a1 on 2025-10-06 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0007_remove_book_core_book_created_e8fd66_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookreview',
            name='accounts_bo_book_id_921817_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookreview',
            name='accounts_bo_is_publ_cfbb5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='readingprogress',
            name='accounts_re_user_id_116278_idx',
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', 'created_at'], name='accounts_bo_book_id_e590ea_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['is_public', 'created_at'], name='accounts_bo_is_publ_ea4236_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['user', 'last_updated'], name='accounts_re_user_id_b930ea_idx'),
        ),
    ]
