# Generated by Django 5.0.3 on 2025-10-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_userprofile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_shelves_list',
            field=models.JSONField(blank=True, default=list, help_text='Lista de nomes de prateleiras personalizadas criadas pelo usuário', verbose_name='Prateleiras Personalizadas'),
        ),
    ]
