# Generated by Django 5.0.3 on 2025-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_custom_shelves_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('none', '⚪ Sem Tema (Padrão Sistema)'), ('fantasy', '✨ Fantasia (Roxo/Dourado)'), ('classic', '📚 Clássicos (Marrom/Bege)'), ('romance', '💕 Romance (Rosa/Vermelho)'), ('scifi', '🚀 Ficção Científica (Azul Neon/Prateado) - PREMIUM'), ('horror', '🎃 Terror (Vermelho Escuro/Preto) - PREMIUM'), ('mystery', '🔍 Mistério (Verde Escuro/Cinza) - PREMIUM'), ('biography', '📖 Biografia (Azul Royal/Dourado) - PREMIUM'), ('poetry', '🌸 Poesia (Lilás/Rosa Claro) - PREMIUM'), ('adventure', '🗺️ Aventura (Laranja/Marrom) - PREMIUM'), ('thriller', '🔪 Thriller (Vermelho/Preto) - PREMIUM'), ('historical', '🏛️ Histórico (Dourado/Marrom) - PREMIUM'), ('selfhelp', '💡 Autoajuda (Amarelo/Laranja) - PREMIUM'), ('philosophy', '🧠 Filosofia (Azul Escuro/Cinza) - PREMIUM'), ('dystopian', '🌆 Distopia (Cinza/Vermelho) - PREMIUM'), ('contemporary', '🎨 Contemporâneo (Multicolor) - PREMIUM')], default='none', help_text='Tema de personalização da biblioteca', max_length=20, verbose_name='Tema Visual'),
        ),
    ]
