# Generated by Django 5.0.3 on 2025-10-16 13:12

import core.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_opacity',
            field=models.IntegerField(default=20, help_text='Opacidade da camada escura sobre o background (0=transparente, 100=opaco)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacidade do Overlay'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_style',
            field=models.CharField(choices=[('cover', 'Cobrir (Cover)'), ('contain', 'Conter (Contain)'), ('repeat', 'Repetir (Repeat)')], default='cover', help_text='Como a imagem de fundo deve ser exibida', max_length=10, verbose_name='Estilo do Background'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_background',
            field=models.ImageField(blank=True, help_text='Imagem de fundo personalizada para a biblioteca (máx. 10MB, apenas PREMIUM)', null=True, storage=core.storage_backends.SupabaseMediaStorage(), upload_to='users/backgrounds/', verbose_name='Background Personalizado'),
        ),
    ]
