# Generated by Django 5.0.3 on 2025-10-19 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_background_opacity_and_more'),
        ('core', '0009_add_purchase_partner_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, help_text='Quando o livro foi abandonado', null=True, verbose_name='Data de Abandono'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='deadline',
            field=models.DateField(blank=True, help_text='Data limite para terminar o livro', null=True, verbose_name='Prazo de Leitura'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='deadline_notified',
            field=models.BooleanField(default=False, help_text='Se já foi notificado sobre o prazo se aproximando', verbose_name='Notificação de Prazo Enviada'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='is_abandoned',
            field=models.BooleanField(default=False, help_text='Se o livro foi marcado como abandonado', verbose_name='Livro Abandonado'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['deadline'], name='accounts_re_deadlin_77e1da_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['is_abandoned'], name='accounts_re_is_aban_973bab_idx'),
        ),
    ]
