# Generated by Django 5.0.3 on 2025-10-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_readingprogress_abandoned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline_warning', 'Prazo Próximo'), ('deadline_passed', 'Prazo Vencido'), ('book_abandoned', 'Livro Abandonado')], max_length=20, verbose_name='Tipo de Notificação')),
                ('message', models.TextField(help_text='Mensagem da notificação', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, help_text='Se a notificação foi lida pelo usuário', verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, help_text='Data e hora em que foi marcada como lida', null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('reading_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.readingprogress', verbose_name='Progresso de Leitura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação de Leitura',
                'verbose_name_plural': 'Notificações de Leitura',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_re_user_id_2c6011_idx'), models.Index(fields=['user', 'created_at'], name='accounts_re_user_id_173d99_idx'), models.Index(fields=['reading_progress'], name='accounts_re_reading_d74dbe_idx')],
            },
        ),
    ]
