# Generated by Django 5.0.3 on 2025-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_readingnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingnotification',
            name='notification_type',
            field=models.CharField(choices=[('deadline_set', 'Prazo Definido'), ('deadline_warning', 'Prazo Próximo'), ('deadline_passed', 'Prazo Vencido'), ('book_abandoned', 'Livro Abandonado')], max_length=20, verbose_name='Tipo de Notificação'),
        ),
    ]
