# Generated by Django 5.0.3 on 2025-10-22 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_readingnotification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingnotification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Texto do botão de ação (ex: "Ver Livro")', max_length=100, null=True, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='readingnotification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Link para onde a notificação direciona', max_length=500, null=True, verbose_name='URL de Ação'),
        ),
        migrations.AddField(
            model_name='readingnotification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dados adicionais específicos do tipo de notificação', verbose_name='Dados Extras'),
        ),
        migrations.AddField(
            model_name='readingnotification',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], db_index=True, default=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='readingnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='readingnotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='readingnotification',
            name='message',
            field=models.TextField(help_text='Conteúdo da notificação', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='readingnotification',
            name='notification_type',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='readingnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AlterField(
            model_name='readingnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Notificação')),
                ('message', models.TextField(help_text='Conteúdo da notificação', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], db_index=True, default=1, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('action_url', models.CharField(blank=True, help_text='Link para onde a notificação direciona', max_length=500, null=True, verbose_name='URL de Ação')),
                ('action_text', models.CharField(blank=True, help_text='Texto do botão de ação (ex: "Ver Livro")', max_length=100, null=True, verbose_name='Texto do Botão')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Dados adicionais específicos do tipo de notificação', verbose_name='Dados Extras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação do Sistema',
                'verbose_name_plural': 'Notificações do Sistema',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_sy_user_id_3c17f4_idx'), models.Index(fields=['user', 'notification_type'], name='accounts_sy_user_id_d5055e_idx')],
            },
        ),
    ]
