# Generated by Django 5.0.3 on 2025-10-24 12:54

import core.storage_backends
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_readingnotification_action_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único e descritivo', max_length=100, unique=True, verbose_name='Nome da Conquista')),
                ('slug', models.SlugField(help_text='Identificador único (gerado automaticamente)', max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descrição detalhada da conquista', max_length=300, verbose_name='Descrição')),
                ('icon', models.CharField(default='🏆', help_text='Emoji ou código FontAwesome', max_length=50, verbose_name='Ícone')),
                ('badge_image', models.ImageField(blank=True, help_text='Imagem visual da conquista (opcional)', null=True, storage=core.storage_backends.SupabaseMediaStorage(), upload_to='achievements/badges/', verbose_name='Imagem do Badge')),
                ('xp_reward', models.IntegerField(default=50, help_text='Quantidade de XP concedida ao completar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Recompensa em XP')),
                ('category', models.CharField(choices=[('reading', '📖 Leitura'), ('progress', '📊 Progresso'), ('social', '💬 Social'), ('diversity', '🌈 Diversidade'), ('special', '⭐ Especial')], default='reading', max_length=20, verbose_name='Categoria')),
                ('difficulty_level', models.IntegerField(choices=[(1, '🟢 Fácil'), (2, '🟡 Médio'), (3, '🟠 Difícil'), (4, '🔴 Muito Difícil'), (5, '🟣 Lendário')], default=2, verbose_name='Dificuldade')),
                ('requirements_json', models.JSONField(default=dict, help_text="\n        Estrutura: {\n            'type': 'books_read' | 'pages_read' | 'streak_days' | 'reviews_written' | 'categories_read',\n            'value': <número>,\n            'condition': 'greater_or_equal' | 'equal' | 'less_or_equal'\n        }\n        ", verbose_name='Requisitos (JSON)')),
                ('is_active', models.BooleanField(default=True, help_text='Conquista disponível para ser completada', verbose_name='Ativo')),
                ('display_order', models.IntegerField(default=0, help_text='Ordem na listagem (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['display_order', 'difficulty_level', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='accounts_ac_categor_417a4d_idx'), models.Index(fields=['difficulty_level'], name='accounts_ac_difficu_a5d6f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único e descritivo', max_length=100, unique=True, verbose_name='Nome do Badge')),
                ('slug', models.SlugField(help_text='Identificador único (gerado automaticamente)', max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descrição curta do badge', max_length=200, verbose_name='Descrição')),
                ('icon', models.CharField(default='🏅', help_text='Emoji ou código FontAwesome', max_length=50, verbose_name='Ícone')),
                ('badge_image', models.ImageField(blank=True, help_text='Imagem visual do badge (recomendado 200x200px)', null=True, storage=core.storage_backends.SupabaseMediaStorage(), upload_to='badges/images/', verbose_name='Imagem do Badge')),
                ('rarity', models.CharField(choices=[('bronze', '🥉 Bronze'), ('silver', '🥈 Prata'), ('gold', '🥇 Ouro'), ('platinum', '💎 Platina'), ('diamond', '💍 Diamante'), ('special', '🌟 Especial')], default='bronze', max_length=20, verbose_name='Raridade')),
                ('category', models.CharField(choices=[('reading', '📖 Leitura'), ('achievement', '🏆 Conquistas'), ('social', '💬 Social'), ('time', '⏰ Tempo'), ('special_event', '🎉 Evento Especial')], default='reading', max_length=20, verbose_name='Categoria')),
                ('requirements_json', models.JSONField(default=dict, help_text="\n        Estrutura flexível para diferentes tipos de requisitos.\n        Exemplos:\n        - {'achievements_count': 10}\n        - {'streak_days': 30}\n        - {'books_read_genre': 'terror', 'count': 5}\n        - {'ranking_position': 10, 'month': 'any'}\n        ", verbose_name='Requisitos (JSON)')),
                ('display_order', models.IntegerField(default=0, help_text='Ordem na listagem (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, help_text='Badge disponível para ser conquistado', verbose_name='Ativo')),
                ('is_limited_edition', models.BooleanField(default=False, help_text='Badge disponível apenas em período limitado', verbose_name='Edição Limitada')),
                ('available_from', models.DateTimeField(blank=True, help_text='Data inicial de disponibilidade (opcional)', null=True, verbose_name='Disponível Desde')),
                ('available_until', models.DateTimeField(blank=True, help_text='Data final de disponibilidade (opcional)', null=True, verbose_name='Disponível Até')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['display_order', 'rarity', 'name'],
                'indexes': [models.Index(fields=['rarity', 'is_active'], name='accounts_ba_rarity_b5ad2f_idx'), models.Index(fields=['category', 'is_active'], name='accounts_ba_categor_ac7c79_idx')],
            },
        ),
        migrations.CreateModel(
            name='XPMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo do evento/promoção', max_length=100, unique=True, verbose_name='Nome do Multiplicador')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do multiplicador', max_length=300, verbose_name='Descrição')),
                ('multiplier_value', models.FloatField(default=1.5, help_text='Multiplicador de XP (1.5 = +50%, 2.0 = +100%, etc)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Valor do Multiplicador')),
                ('start_date', models.DateTimeField(help_text='Quando o multiplicador começa a valer', verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(help_text='Quando o multiplicador termina', verbose_name='Data de Término')),
                ('applies_to', models.CharField(choices=[('all', 'Todos os Usuários'), ('premium', 'Apenas Premium'), ('free', 'Apenas Free')], default='all', help_text='Quem pode usar este multiplicador', max_length=20, verbose_name='Aplica-se a')),
                ('is_active', models.BooleanField(default=True, help_text='Multiplicador está ativo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Multiplicador de XP',
                'verbose_name_plural': 'Multiplicadores de XP',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='accounts_xp_is_acti_5fdac5_idx'), models.Index(fields=['applies_to'], name='accounts_xp_applies_b12e45_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Mês do ranking (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('year', models.IntegerField(help_text='Ano do ranking', verbose_name='Ano')),
                ('total_xp', models.IntegerField(default=0, help_text='XP ganho durante este mês', validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP Total do Mês')),
                ('books_read', models.IntegerField(default=0, help_text='Livros finalizados no mês', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Livros Lidos')),
                ('pages_read', models.IntegerField(default=0, help_text='Total de páginas lidas no mês', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Páginas Lidas')),
                ('reviews_written', models.IntegerField(default=0, help_text='Reviews publicadas no mês', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reviews Escritas')),
                ('achievements_earned', models.IntegerField(default=0, help_text='Conquistas completadas no mês', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conquistas Desbloqueadas')),
                ('consecutive_reading_days', models.IntegerField(default=0, help_text='Maior streak de dias de leitura no mês', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dias Consecutivos de Leitura')),
                ('total_score', models.IntegerField(default=0, help_text='Pontuação calculada para ranking', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontuação Total')),
                ('rank_position', models.IntegerField(default=0, help_text='Posição atual no ranking mensal (0 = não ranqueado)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Posição no Ranking')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rankings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ranking Mensal',
                'verbose_name_plural': 'Rankings Mensais',
                'ordering': ['year', 'month', 'rank_position'],
                'indexes': [models.Index(fields=['month', 'year', 'rank_position'], name='accounts_mo_month_ecce53_idx'), models.Index(fields=['total_score'], name='accounts_mo_total_s_2100aa_idx')],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Porcentagem de conclusão (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progresso (%)')),
                ('is_completed', models.BooleanField(default=False, help_text='True se a conquista foi completada', verbose_name='Completada')),
                ('earned_at', models.DateTimeField(blank=True, help_text='Data/hora que completou a conquista', null=True, verbose_name='Conquistada Em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='accounts.achievement', verbose_name='Conquista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'ordering': ['-earned_at', '-progress_percentage'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='accounts_us_user_id_fef049_idx'), models.Index(fields=['achievement', 'is_completed'], name='accounts_us_achieve_0f9987_idx')],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_showcased', models.BooleanField(default=False, help_text='Badge será exibido no perfil do usuário', verbose_name='Exibir no Perfil')),
                ('showcase_order', models.IntegerField(default=0, help_text='Ordem no showcase (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Conquistado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='accounts.badge', verbose_name='Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Badge do Usuário',
                'verbose_name_plural': 'Badges dos Usuários',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'is_showcased'], name='accounts_us_user_id_6b32a0_idx'), models.Index(fields=['badge'], name='accounts_us_badge_i_b7f024_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
