# Generated by Django 5.0.3 on 2025-11-04 11:05

import core.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_achievement_badge_xpmultiplier_monthlyranking_and_more'),
        ('finance', '0004_campaign_send_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil (máx. 5MB, 500x500px)', null=True, storage=core.storage_backends.SupabaseMediaStorage(), upload_to='users/avatars/', verbose_name='Avatar'),
        ),
        migrations.CreateModel(
            name='CampaignNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Notificação')),
                ('message', models.TextField(help_text='Conteúdo da notificação', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], db_index=True, default=1, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('action_url', models.CharField(blank=True, help_text='Link para onde a notificação direciona', max_length=500, null=True, verbose_name='URL de Ação')),
                ('action_text', models.CharField(blank=True, help_text='Texto do botão de ação (ex: "Ver Livro")', max_length=100, null=True, verbose_name='Texto do Botão')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Dados adicionais específicos do tipo de notificação', verbose_name='Dados Extras')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finance.campaign', verbose_name='Campanha')),
                ('campaign_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='finance.campaigngrant', verbose_name='Concessão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação de Campanha',
                'verbose_name_plural': 'Notificações de Campanhas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'notification_type', '-created_at'], name='accounts_ca_user_id_eb2f17_idx'), models.Index(fields=['campaign', '-created_at'], name='accounts_ca_campaig_15e3e4_idx')],
            },
        ),
    ]
