# Generated by Django 5.1.1 on 2025-11-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_campaign_notification_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignnotification',
            new_name='accounts_ca_user_id_db7d9d_idx',
            old_name='accounts_ca_user_id_is_read_idx',
        ),
    ]
