# Generated by Django 5.1.1 on 2025-12-04 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_accounts_ca_user_id_is_read_idx_accounts_ca_user_id_db7d9d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username do usuário que foi excluído', max_length=150, verbose_name='Nome de usuário')),
                ('email', models.EmailField(help_text='Email do usuário excluído', max_length=254, verbose_name='Email')),
                ('user_id', models.IntegerField(help_text='ID original do usuário no banco de dados', verbose_name='ID do usuário')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que a conta foi excluída', verbose_name='Data de exclusão')),
                ('user_created_at', models.DateTimeField(blank=True, help_text='Data de criação da conta do usuário', null=True, verbose_name='Conta criada em')),
                ('deletion_reason', models.CharField(choices=[('nao_uso_mais', 'Não uso mais o serviço'), ('falta_funcionalidades', 'Falta de funcionalidades necessárias'), ('dificuldade_uso', 'Dificuldade de uso / Interface confusa'), ('problemas_tecnicos', 'Problemas técnicos recorrentes'), ('preco_premium', 'Preço do Premium muito alto'), ('privacidade', 'Preocupações com privacidade'), ('migrando_plataforma', 'Migrando para outra plataforma'), ('conta_duplicada', 'Conta duplicada'), ('outros', 'Outros motivos'), ('nao_informado', 'Não informado')], default='nao_informado', help_text='Motivo selecionado pelo usuário', max_length=50, verbose_name='Motivo da exclusão')),
                ('other_reason', models.CharField(blank=True, help_text="Motivo customizado quando selecionado 'Outros'", max_length=255, null=True, verbose_name='Motivo personalizado')),
                ('was_premium', models.BooleanField(default=False, help_text='Se o usuário tinha assinatura Premium ativa', verbose_name='Era Premium')),
                ('books_count', models.IntegerField(default=0, help_text='Número de livros na biblioteca do usuário', verbose_name='Quantidade de livros')),
                ('days_as_member', models.IntegerField(blank=True, help_text='Quantos dias o usuário foi membro da plataforma', null=True, verbose_name='Dias como membro')),
                ('email_sent', models.BooleanField(default=False, help_text='Se o email de confirmação foi enviado com sucesso', verbose_name='Email enviado')),
                ('email_error', models.TextField(blank=True, help_text='Mensagem de erro caso o email tenha falhado', null=True, verbose_name='Erro no email')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Data e hora em que o email foi enviado', null=True, verbose_name='Email enviado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de onde a exclusão foi solicitada', null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador/dispositivo', null=True, verbose_name='User Agent')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas ou observações da equipe administrativa', null=True, verbose_name='Notas administrativas')),
            ],
            options={
                'verbose_name': 'Exclusão de Conta',
                'verbose_name_plural': 'Exclusões de Contas',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['-deleted_at'], name='accounts_ac_deleted_137bf1_idx'), models.Index(fields=['deletion_reason'], name='accounts_ac_deletio_20f133_idx'), models.Index(fields=['was_premium'], name='accounts_ac_was_pre_c63c22_idx'), models.Index(fields=['email_sent'], name='accounts_ac_email_s_131c56_idx')],
            },
        ),
    ]
