# Generated by Django 5.1.1 on 2025-12-20 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_accountdeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_position_x',
            field=models.IntegerField(default=50, help_text='Posição horizontal (%): 0=esquerda, 50=centro, 100=direita', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Posição X do Banner'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_position_y',
            field=models.IntegerField(default=50, help_text='Posição vertical (%): 0=topo, 50=centro, 100=baixo', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Posição Y do Banner'),
        ),
    ]
