# Generated by Django 5.1.1 on 2026-03-12 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_reviewcomment_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Nota de 0.0 a 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Avaliação'),
        ),
    ]
