# Generated by Django 5.1.1 on 2026-06-17

from django.db import migrations

def create_initial_badges(apps, schema_editor):
    Badge = apps.get_model('accounts', 'Badge')
    
    badges_data = [
        {
            'name': 'Membro Premium',
            'slug': 'membro-premium',
            'description': 'Concedido a membros que apoiam a CGBookStore com uma assinatura Premium.',
            'icon': '👑',
            'rarity': 'gold',
            'category': 'special_event',
            'display_order': 1,
            'is_active': True,
            'requirements_json': {'premium_subscriber': True},
        },
        {
            'name': 'Voz do Debate',
            'slug': 'voz-do-debate',
            'description': 'Concedido a quem participa pela primeira vez de um debate literário na CGBookStore.',
            'icon': '💬',
            'rarity': 'silver',
            'category': 'social',
            'display_order': 2,
            'is_active': True,
            'requirements_json': {'debate_participant': True},
        },
        {
            'name': 'Mestre do Quiz',
            'slug': 'mestre-do-quiz',
            'description': 'Concedido a quem completa um quiz literário pela primeira vez na CGBookStore.',
            'icon': '🧠',
            'rarity': 'silver',
            'category': 'achievement',
            'display_order': 3,
            'is_active': True,
            'requirements_json': {'quiz_participant': True},
        }
    ]
    
    for badge_info in badges_data:
        Badge.objects.get_or_create(
            slug=badge_info['slug'],
            defaults={
                'name': badge_info['name'],
                'description': badge_info['description'],
                'icon': badge_info['icon'],
                'rarity': badge_info['rarity'],
                'category': badge_info['category'],
                'display_order': badge_info['display_order'],
                'is_active': badge_info['is_active'],
                'requirements_json': badge_info['requirements_json'],
            }
        )

def remove_initial_badges(apps, schema_editor):
    Badge = apps.get_model('accounts', 'Badge')
    slugs = ['membro-premium', 'voz-do-debate', 'mestre-do-quiz']
    Badge.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rating_decimal_field'),
    ]

    operations = [
        migrations.RunPython(create_initial_badges, remove_initial_badges),
    ]
