# Generated by Django 5.1.1 on 2026-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_create_initial_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica se a leitura foi validada por IA/Scanner e conta para o ranking', verbose_name='Leitura Verificada'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='isbn_scanned',
            field=models.BooleanField(default=False, help_text='Indica se o livro foi inserido através do escaneamento do código de barras físico', verbose_name='ISBN Escaneado'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='progress_updates_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de atualizações de progresso feitas em dias diferentes', verbose_name='Quantidade de Atualizações'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='verification_image',
            field=models.ImageField(blank=True, help_text='Foto da página solicitada enviada pelo usuário', null=True, upload_to='reading_verifications/', verbose_name='Imagem de Verificação'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Feedback detalhado do resultado da verificação (retornado pelo Gemini ou moderador)', verbose_name='Notas da Verificação'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='verification_page',
            field=models.PositiveIntegerField(blank=True, help_text='Número da página sorteada pelo sistema para comprovação de leitura', null=True, verbose_name='Página de Verificação'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pendente de Envio'), ('verifying', 'Verificando com IA'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('manual_review', 'Revisão Manual Necessária')], default='pending', max_length=20, verbose_name='Status da Verificação'),
        ),
    ]
