# Generated by Django 5.1.1 on 2026-02-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('author', models.CharField(max_length=300, verbose_name='Autor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cover_image', models.URLField(blank=True, verbose_name='URL da Capa')),
                ('epub_file', models.FileField(blank=True, null=True, upload_to='ebooks/', verbose_name='Arquivo EPUB')),
                ('epub_url', models.URLField(blank=True, help_text='Para livros externos', verbose_name='URL do EPUB')),
                ('source', models.CharField(choices=[('gutenberg', 'Project Gutenberg'), ('openlibrary', 'Open Library'), ('upload', 'Upload Manual'), ('archive', 'Internet Archive')], default='gutenberg', max_length=20, verbose_name='Fonte')),
                ('external_id', models.CharField(blank=True, help_text='ID na fonte externa (ex: Gutenberg ID)', max_length=100, verbose_name='ID Externo')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('other', 'Outro')], default='pt', max_length=10, verbose_name='Idioma')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Editora')),
                ('publish_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('subjects', models.JSONField(blank=True, default=list, verbose_name='Assuntos/Categorias')),
                ('is_public_domain', models.BooleanField(default=True, verbose_name='Domínio Público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='Leituras Completas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'E-Book',
                'verbose_name_plural': 'E-Books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='ereader_ebo_source_e70f6a_idx'), models.Index(fields=['language'], name='ereader_ebo_languag_818afa_idx'), models.Index(fields=['is_active'], name='ereader_ebo_is_acti_ecb0cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(help_text='Posição do marcador', max_length=500, verbose_name='CFI')),
                ('title', models.CharField(blank=True, help_text='Nome personalizado para o marcador', max_length=200, verbose_name='Título')),
                ('chapter_title', models.CharField(blank=True, max_length=300, verbose_name='Título do Capítulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereader_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='ereader.ebook')),
            ],
            options={
                'verbose_name': 'Marcador',
                'verbose_name_plural': 'Marcadores',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi_range', models.CharField(help_text='Intervalo de texto destacado', max_length=1000, verbose_name='CFI Range')),
                ('text', models.TextField(verbose_name='Texto Destacado')),
                ('color', models.CharField(choices=[('yellow', 'Amarelo'), ('green', 'Verde'), ('blue', 'Azul'), ('pink', 'Rosa'), ('orange', 'Laranja')], default='yellow', max_length=20, verbose_name='Cor')),
                ('chapter_title', models.CharField(blank=True, max_length=300, verbose_name='Título do Capítulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='ereader.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereader_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('amber', 'Âmbar (Vintage)'), ('green', 'Verde Fósforo'), ('sepia', 'Sépia'), ('light', 'Claro'), ('dark', 'Escuro')], default='amber', max_length=20, verbose_name='Tema')),
                ('font_family', models.CharField(choices=[('serif', 'Serif (Clássico)'), ('sans', 'Sans-serif (Moderno)'), ('mono', 'Monospace (Console)')], default='serif', max_length=20, verbose_name='Fonte')),
                ('font_size', models.PositiveIntegerField(default=18, verbose_name='Tamanho da Fonte')),
                ('line_height', models.DecimalField(decimal_places=1, default=1.6, max_digits=3, verbose_name='Espaçamento de Linha')),
                ('scanlines_enabled', models.BooleanField(default=True, verbose_name='Scanlines')),
                ('crt_curvature', models.BooleanField(default=True, verbose_name='Curvatura CRT')),
                ('screen_glow', models.BooleanField(default=True, verbose_name='Brilho da Tela')),
                ('sound_effects', models.BooleanField(default=True, verbose_name='Efeitos Sonoros')),
                ('auto_save_progress', models.BooleanField(default=True, verbose_name='Salvar Progresso Automaticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ereader_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurações do Leitor',
                'verbose_name_plural': 'Configurações dos Leitores',
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(help_text='Posição da nota no livro', max_length=500, verbose_name='CFI')),
                ('note_text', models.TextField(verbose_name='Nota')),
                ('chapter_title', models.CharField(blank=True, max_length=300, verbose_name='Título do Capítulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_notes', to='ereader.ebook')),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='ereader.highlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereader_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Leitura',
                'verbose_name_plural': 'Notas de Leitura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cfi', models.CharField(blank=True, help_text='Identificador de posição do epub.js', max_length=500, verbose_name='CFI Atual')),
                ('current_chapter', models.PositiveIntegerField(default=0, verbose_name='Capítulo Atual')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progresso (%)')),
                ('total_reading_time', models.PositiveIntegerField(default=0, verbose_name='Tempo de Leitura (minutos)')),
                ('last_session_duration', models.PositiveIntegerField(default=0, verbose_name='Última Sessão (minutos)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('last_read', models.DateTimeField(auto_now=True, verbose_name='Última Leitura')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='ereader.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereader_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Leitura',
                'verbose_name_plural': 'Progressos de Leitura',
                'ordering': ['-last_read'],
                'unique_together': {('user', 'ebook')},
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_libraries', to='ereader.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereader_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biblioteca do Usuário',
                'verbose_name_plural': 'Bibliotecas dos Usuários',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'ebook')},
            },
        ),
    ]
