# Generated by Django 5.1.1 on 2026-05-29 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot_literario', '0004_alter_chatbotknowledge_knowledge_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('user_complaint', 'Reclamação Direta do Usuário'), ('negative_feedback', 'Feedback Negativo (👎)'), ('api_error', 'Erro de API da IA'), ('timeout', 'Timeout na resposta da IA'), ('empty_response', 'Resposta Vazia'), ('hallucination_suspected', 'Possível Alucinação da IA'), ('quota_exceeded', 'Quota da API Excedida'), ('content_filter', 'Filtro de Conteúdo Ativado'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Severidade')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Provedor de IA')),
                ('user_complaint_text', models.TextField(blank=True, help_text='Texto descrito pelo usuário ao reportar o problema', verbose_name='Texto da Reclamação')),
                ('ai_response_preview', models.TextField(blank=True, help_text='Primeiros 500 caracteres da resposta problemática', verbose_name='Prévia da Resposta da IA')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro retornada pela API da IA', verbose_name='Mensagem de Erro Técnico')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alerta WhatsApp Enviado')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Alerta Enviado em')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolution_notes', models.TextField(blank=True, help_text='O que foi feito para resolver o problema', verbose_name='Notas de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_alerts', to='chatbot_literario.chatmessage', verbose_name='Mensagem da IA')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ai_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido Por')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_alerts', to='chatbot_literario.chatsession', verbose_name='Sessão de Chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Afetado')),
            ],
            options={
                'verbose_name': 'Alerta de IA',
                'verbose_name_plural': 'Alertas de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='monitoring__severit_9c0026_idx'), models.Index(fields=['alert_type', '-created_at'], name='monitoring__alert_t_d5cb56_idx'), models.Index(fields=['resolved', '-created_at'], name='monitoring__resolve_703193_idx'), models.Index(fields=['provider', '-created_at'], name='monitoring__provide_8ab0a2_idx'), models.Index(fields=['alert_sent'], name='monitoring__alert_s_f28733_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('abusive_language', 'Linguagem Abusiva/Ofensiva'), ('spam', 'Spam (mensagens repetitivas)'), ('jailbreak_attempt', 'Tentativa de Jailbreak da IA'), ('illegal_content', 'Solicitação de Conteúdo Ilegal'), ('harassment', 'Assédio ou Ameaças'), ('personal_data_solicitation', 'Solicitação de Dados Pessoais'), ('other', 'Outro')], default='other', max_length=40, verbose_name='Tipo de Atividade')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Severidade')),
                ('detected_keywords', models.JSONField(blank=True, default=list, help_text='Lista de palavras ou padrões que ativaram o detector', verbose_name='Palavras/Padrões Detectados')),
                ('message_content', models.TextField(help_text='Conteúdo da mensagem que gerou o alerta', verbose_name='Conteúdo da Mensagem')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Chave de Sessão Anônima')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Usuário')),
                ('alert_sent', models.BooleanField(default=False, help_text='Se o alerta via WhatsApp já foi enviado ao administrador', verbose_name='Alerta WhatsApp Enviado')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Alerta Enviado em')),
                ('reviewed', models.BooleanField(default=False, help_text='Se o administrador já revisou esta ocorrência', verbose_name='Revisado pelo Admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Observações do administrador após revisão', verbose_name='Notas do Revisor')),
                ('action_taken', models.CharField(blank=True, choices=[('none', 'Nenhuma ação'), ('warned', 'Usuário advertido'), ('suspended', 'Usuário suspenso'), ('banned', 'Usuário banido'), ('false_positive', 'Falso positivo')], max_length=50, verbose_name='Ação Tomada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='chatbot_literario.chatmessage', verbose_name='Mensagem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='chatbot_literario.chatsession', verbose_name='Sessão de Chat')),
                ('user', models.ForeignKey(blank=True, help_text='Nulo para usuários anônimos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atividade Suspeita',
                'verbose_name_plural': 'Atividades Suspeitas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='monitoring__severit_1f8a3f_idx'), models.Index(fields=['activity_type', '-created_at'], name='monitoring__activit_00f941_idx'), models.Index(fields=['reviewed', '-created_at'], name='monitoring__reviewe_1e2cfa_idx'), models.Index(fields=['user', '-created_at'], name='monitoring__user_id_c316f5_idx'), models.Index(fields=['alert_sent'], name='monitoring__alert_s_a88f16_idx')],
            },
        ),
    ]
