# Generated by Django 5.1.1 on 2026-07-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(help_text='Ex: chatbot, recommendations, book_review, home_personalization, news_generation', max_length=50, verbose_name='Recurso/Funcionalidade')),
                ('provider', models.CharField(help_text='Ex: gemini, groq, openai, claude, local', max_length=30, verbose_name='Provedor')),
                ('model_name', models.CharField(help_text='Ex: gemini-2.5-flash, llama-3.1-70b, gpt-4o, etc.', max_length=50, verbose_name='Modelo')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Tokens do Prompt')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Tokens da Resposta')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Tokens Totais')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Custo Estimado (USD)')),
                ('response_time_seconds', models.FloatField(default=0.0, verbose_name='Tempo de Resposta (segundos)')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failure', 'Falha')], default='success', max_length=15, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Uso da IA',
                'verbose_name_plural': 'Logs de Uso da IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='monitoring__provide_86d59f_idx'), models.Index(fields=['feature_name', '-created_at'], name='monitoring__feature_699d75_idx'), models.Index(fields=['user', '-created_at'], name='monitoring__user_id_2d8c6d_idx'), models.Index(fields=['created_at'], name='monitoring__created_7c1a29_idx')],
            },
        ),
    ]
