# Generated by Django 5.1.1 on 2025-11-28 13:15

import django.core.validators
import django.db.models.deletion
import new_authors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergingAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Conte sua história como escritor', max_length=2000, verbose_name='Biografia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=new_authors.models.author_photo_path, verbose_name='Foto do Autor')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter/X')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('total_views', models.IntegerField(default=0, verbose_name='Total de Visualizações')),
                ('total_books', models.IntegerField(default=0, verbose_name='Total de Livros')),
                ('total_followers', models.IntegerField(default=0, verbose_name='Total de Seguidores')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emerging_author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autor Emergente',
                'verbose_name_plural': 'Autores Emergentes',
                'db_table': 'new_authors_emerging_author',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('synopsis', models.TextField(help_text='Breve descrição do livro', max_length=1000, verbose_name='Sinopse')),
                ('description', models.TextField(help_text='Descrição detalhada do livro e enredo', verbose_name='Descrição Completa')),
                ('cover_image', models.ImageField(help_text='Recomendado: 600x900px', upload_to=new_authors.models.book_cover_path, verbose_name='Capa do Livro')),
                ('genre', models.CharField(choices=[('fiction', 'Ficção'), ('romance', 'Romance'), ('fantasy', 'Fantasia'), ('scifi', 'Ficção Científica'), ('mystery', 'Mistério'), ('thriller', 'Thriller'), ('horror', 'Terror'), ('adventure', 'Aventura'), ('historical', 'Histórico'), ('biography', 'Biografia'), ('poetry', 'Poesia'), ('other', 'Outro')], max_length=20, verbose_name='Gênero')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em Revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('views_count', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avaliação Média')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Total de Avaliações')),
                ('estimated_pages', models.IntegerField(default=0, verbose_name='Páginas Estimadas')),
                ('language', models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='new_authors.emergingauthor')),
            ],
            options={
                'verbose_name': 'Livro de Autor Emergente',
                'verbose_name_plural': 'Livros de Autores Emergentes',
                'db_table': 'new_authors_book',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da Editora')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, upload_to='new_authors/publishers/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('authors_contacted', models.IntegerField(default=0, verbose_name='Autores Contatados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'db_table': 'new_authors_publisher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensagem da editora para o autor', max_length=1000, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('contacted', 'Contatado'), ('negotiating', 'Negociando'), ('closed', 'Finalizado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_interests', to='new_authors.authorbook')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='new_authors.publisherprofile')),
            ],
            options={
                'verbose_name': 'Interesse de Editora',
                'verbose_name_plural': 'Interesses de Editoras',
                'db_table': 'new_authors_publisher_interest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorBookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('comment', models.TextField(max_length=2000, verbose_name='Comentário')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Útil')),
                ('report_count', models.IntegerField(default=0, verbose_name='Denúncias')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='new_authors.authorbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emerging_book_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'new_authors_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', '-created_at'], name='idx_review_book_date'), models.Index(fields=['user'], name='idx_review_user'), models.Index(fields=['is_approved', '-helpful_count'], name='idx_review_approved')],
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BookFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_chapter', models.BooleanField(default=True, verbose_name='Notificar novos capítulos')),
                ('notify_updates', models.BooleanField(default=True, verbose_name='Notificar atualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Seguindo desde')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='new_authors.authorbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguidor de Livro',
                'verbose_name_plural': 'Seguidores de Livros',
                'db_table': 'new_authors_follower',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book'], name='idx_follower_book'), models.Index(fields=['user'], name='idx_follower_user')],
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número do Capítulo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
                ('content', models.TextField(help_text='Texto completo do capítulo', verbose_name='Conteúdo')),
                ('file', models.FileField(blank=True, help_text='PDF, DOCX ou TXT', null=True, upload_to=new_authors.models.chapter_file_path, verbose_name='Arquivo')),
                ('preview', models.TextField(blank=True, help_text='Primeiras linhas do capítulo', max_length=500, verbose_name='Preview')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('is_free', models.BooleanField(default=True, help_text='Se falso, requer login para ler', verbose_name='Gratuito')),
                ('word_count', models.IntegerField(default=0, verbose_name='Contagem de Palavras')),
                ('views_count', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='new_authors.authorbook')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'db_table': 'new_authors_chapter',
                'ordering': ['book', 'number'],
                'indexes': [models.Index(fields=['book', 'number'], name='idx_chapter_book_num'), models.Index(fields=['is_published'], name='idx_chapter_published')],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='emergingauthor',
            index=models.Index(fields=['user'], name='idx_emerging_author_user'),
        ),
        migrations.AddIndex(
            model_name='emergingauthor',
            index=models.Index(fields=['-total_views'], name='idx_emerging_author_views'),
        ),
        migrations.AddIndex(
            model_name='emergingauthor',
            index=models.Index(fields=['is_verified', 'is_active'], name='idx_emerging_author_status'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['author', '-published_at'], name='idx_book_author_date'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['status'], name='idx_book_status'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['genre'], name='idx_book_genre'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['-rating_average'], name='idx_book_rating'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['-views_count'], name='idx_book_views'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['slug'], name='idx_book_slug'),
        ),
        migrations.AddIndex(
            model_name='publisherprofile',
            index=models.Index(fields=['is_verified', 'is_active'], name='idx_publisher_status'),
        ),
        migrations.AddIndex(
            model_name='publisherinterest',
            index=models.Index(fields=['publisher', '-created_at'], name='idx_interest_publisher'),
        ),
        migrations.AddIndex(
            model_name='publisherinterest',
            index=models.Index(fields=['book', '-created_at'], name='idx_interest_book'),
        ),
        migrations.AddIndex(
            model_name='publisherinterest',
            index=models.Index(fields=['status'], name='idx_interest_status'),
        ),
        migrations.AlterUniqueTogether(
            name='publisherinterest',
            unique_together={('publisher', 'book')},
        ),
    ]
