# Generated by Django 5.1.1 on 2025-11-29 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='author_notes',
            field=models.TextField(blank=True, help_text='Notas ou comentários do autor sobre o capítulo', verbose_name='Notas do Autor'),
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descrição detalhada do livro e enredo', verbose_name='Descrição Completa'),
        ),
        migrations.CreateModel(
            name='BookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Curtido em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='new_authors.authorbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curtida de Livro',
                'verbose_name_plural': 'Curtidas de Livros',
                'db_table': 'new_authors_book_like',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book'], name='idx_like_book'), models.Index(fields=['user'], name='idx_like_user')],
                'unique_together': {('book', 'user')},
            },
        ),
    ]
