# Generated by Django 5.1.1 on 2025-12-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_authors', '0002_add_missing_fields'),
        ('new_authors', '0002_chapter_author_notes_alter_authorbook_description_and_more'),
    ]

    operations = [
    ]

