# Generated by Django 5.1.1 on 2025-12-09 22:19

import django.db.models.deletion
import new_authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_authors', '0005_authorplan_publisherplan_authorsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Termo de Responsabilidade - Autores Emergentes', max_length=200, verbose_name='Título')),
                ('version', models.CharField(help_text='Ex: 1.0, 1.1, 2.0', max_length=20, unique=True, verbose_name='Versão')),
                ('content', models.TextField(help_text='Texto completo do termo de responsabilidade em markdown ou HTML', verbose_name='Conteúdo do Termo')),
                ('summary_points', models.JSONField(default=list, help_text='Lista dos pontos principais do termo para exibição rápida', verbose_name='Pontos Principais')),
                ('is_active', models.BooleanField(default=True, verbose_name='Versão Ativa')),
                ('is_current', models.BooleanField(default=False, help_text='Apenas uma versão pode ser a atual', verbose_name='Versão Atual')),
                ('effective_date', models.DateTimeField(help_text='Data em que este termo entra em vigor', verbose_name='Data de Vigência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade',
                'verbose_name_plural': 'Termos de Responsabilidade',
                'db_table': 'new_authors_terms_of_service',
                'ordering': ['-version'],
            },
        ),
        migrations.RemoveField(
            model_name='authorsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='authorsubscription',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dealcommission',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dealcommission',
            name='book',
        ),
        migrations.RemoveField(
            model_name='dealcommission',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='manuscriptdownload',
            name='book',
        ),
        migrations.RemoveField(
            model_name='manuscriptdownload',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='manuscriptdownload',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publishersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='publishersubscription',
            name='publisher',
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='accepted_terms',
            field=models.BooleanField(default=False, help_text='É obrigatório aceitar os termos para continuar', verbose_name='Aceito os Termos de Uso'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termos Aceitos em'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notas internas sobre a aprovação/rejeição', verbose_name='Observações do Admin'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Você deve ter no mínimo 18 anos (obrigatório para aprovação)', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='cep',
            field=models.CharField(blank=True, default='', help_text='Formato: 00000-000 (obrigatório para aprovação)', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='cpf',
            field=models.CharField(blank=True, default='', help_text='CPF para validação (formato: 000.000.000-00) - obrigatório para aprovação', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='cpf_document',
            field=models.FileField(blank=True, help_text='Upload do CPF em PDF', null=True, upload_to='new_authors/documents/', verbose_name='Comprovante de CPF'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Nome completo como aparecerá nas publicações (obrigatório para aprovação)', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='identity_document',
            field=models.FileField(blank=True, help_text='Upload de RG ou CNH (frente e verso em PDF) - obrigatório para aprovação', null=True, upload_to='new_authors/documents/', verbose_name='Documento de Identidade'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='literary_experience',
            field=models.TextField(blank=True, default='', help_text='Descreva sua experiência anterior: prêmios, publicações, cursos, etc.', max_length=1000, verbose_name='Experiência Literária'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Formato: (00) 00000-0000 (obrigatório para aprovação)', max_length=20, verbose_name='Telefone/Celular'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='proof_of_address',
            field=models.FileField(blank=True, help_text='Conta de luz, água ou telefone (últimos 3 meses) - obrigatório para aprovação', null=True, upload_to='new_authors/documents/', verbose_name='Comprovante de Residência'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejeitado em'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo caso o cadastro seja rejeitado', verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='state',
            field=models.CharField(blank=True, default='', help_text='UF (ex: SP, RJ, MG)', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('reviewing', 'Em Análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='pending', help_text='Status do cadastro perante o admin', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rua/Avenida'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='terms_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceitação dos Termos'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='writing_genres',
            field=models.JSONField(blank=True, default=list, help_text='Gêneros literários que você escreve', verbose_name='Gêneros de Escrita'),
        ),
        migrations.AlterField(
            model_name='emergingauthor',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Conte sua história como escritor, experiências e objetivos (obrigatório para aprovação)', max_length=2000, verbose_name='Biografia Literária'),
        ),
        migrations.AlterField(
            model_name='emergingauthor',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='emergingauthor',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='E-mail Verificado'),
        ),
        migrations.AlterField(
            model_name='emergingauthor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto profissional (obrigatória para aprovação)', null=True, upload_to=new_authors.models.author_photo_path, verbose_name='Foto do Autor'),
        ),
        migrations.AlterField(
            model_name='emergingauthor',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website Pessoal'),
        ),
        migrations.AddField(
            model_name='emergingauthor',
            name='accepted_terms_version',
            field=models.ForeignKey(blank=True, help_text='Versão específica do termo que foi aceita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by_authors', to='new_authors.authortermsofservice', verbose_name='Versão do Termo Aceita'),
        ),
        migrations.DeleteModel(
            name='AuthorPlan',
        ),
        migrations.DeleteModel(
            name='AuthorSubscription',
        ),
        migrations.DeleteModel(
            name='DealCommission',
        ),
        migrations.DeleteModel(
            name='ManuscriptDownload',
        ),
        migrations.DeleteModel(
            name='PublisherPlan',
        ),
        migrations.DeleteModel(
            name='PublisherSubscription',
        ),
    ]
