# Generated by Django 5.1.1 on 2025-12-10 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_authors', '0006_authortermsofservice_remove_authorsubscription_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherprofile',
            name='cnpj',
            field=models.CharField(blank=True, default='', help_text='CNPJ da editora (formato: XX.XXX.XXX/XXXX-XX)', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddIndex(
            model_name='publisherprofile',
            index=models.Index(fields=['cnpj'], name='idx_publisher_cnpj'),
        ),
    ]
