# Generated by Django 5.1.1 on 2026-07-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_interest', models.JSONField(blank=True, default=dict, help_text="Dicionário com categorias e notas de afinidade de 0.0 a 1.0 (ex: {'Fantasia': 0.85})", verbose_name='Afinidades por Categoria')),
                ('authors_interest', models.JSONField(blank=True, default=dict, help_text="Dicionário com autores e notas de afinidade de 0.0 a 1.0 (ex: {'J.R.R. Tolkien': 0.90})", verbose_name='Afinidades por Autor')),
                ('reading_style_ai', models.JSONField(blank=True, default=dict, help_text='Metadados do estilo de leitura (humor preferido, ritmo de leitura, complexidade preferida)', verbose_name='Estilo de Leitura IA')),
                ('profile_summary', models.TextField(blank=True, help_text='Resumo descritivo da jornada e do perfil literário do usuário gerado por IA', verbose_name='Biografia de Leitura IA')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Último Cálculo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reader_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Literário de IA',
                'verbose_name_plural': 'Perfis Literários de IA',
                'db_table': 'recommendations_ai_reader_profile',
            },
        ),
    ]
